/*
 * This file was automatically generated by EvoSuite
 * Sun Apr 13 14:24:55 GMT 2025
 */

package sqlancer.cnosdb.ast;

import org.junit.Test;
import static org.junit.Assert.*;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;
import sqlancer.cnosdb.ast.CnosDBAlias;
import sqlancer.cnosdb.ast.CnosDBConstant;
import sqlancer.cnosdb.ast.CnosDBExpression;
import sqlancer.common.visitor.UnaryOperation;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true) 
public class CnosDBAlias_ESTest extends CnosDBAlias_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      CnosDBConstant.TimeStampConstant cnosDBConstant_TimeStampConstant0 = new CnosDBConstant.TimeStampConstant(9223372036854775807L);
      CnosDBAlias cnosDBAlias0 = new CnosDBAlias(cnosDBConstant_TimeStampConstant0, ";");
      CnosDBConstant.TimeStampConstant cnosDBConstant_TimeStampConstant1 = (CnosDBConstant.TimeStampConstant)cnosDBAlias0.getExpression();
      assertEquals(9223372036854775807L, cnosDBConstant_TimeStampConstant1.asInt());
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      CnosDBAlias cnosDBAlias0 = new CnosDBAlias((CnosDBExpression) null, "");
      String string0 = cnosDBAlias0.getOperatorRepresentation();
      assertEquals(" as ", string0);
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      CnosDBAlias cnosDBAlias0 = new CnosDBAlias((CnosDBExpression) null, "");
      boolean boolean0 = cnosDBAlias0.omitBracketsWhenPrinting();
      assertTrue(boolean0);
  }

  @Test(timeout = 4000)
  public void test3()  throws Throwable  {
      CnosDBAlias cnosDBAlias0 = new CnosDBAlias((CnosDBExpression) null, "");
      UnaryOperation.OperatorKind unaryOperation_OperatorKind0 = cnosDBAlias0.getOperatorKind();
      assertEquals(UnaryOperation.OperatorKind.POSTFIX, unaryOperation_OperatorKind0);
  }

  @Test(timeout = 4000)
  public void test4()  throws Throwable  {
      CnosDBAlias cnosDBAlias0 = new CnosDBAlias((CnosDBExpression) null, " )s ");
      CnosDBExpression cnosDBExpression0 = cnosDBAlias0.getExpression();
      assertNull(cnosDBExpression0);
  }
}
