/*
 * This file was automatically generated by EvoSuite
 * Mon Apr 14 03:48:08 GMT 2025
 */

package sqlancer.cnosdb.ast;

import org.junit.Test;
import static org.junit.Assert.*;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;
import sqlancer.cnosdb.CnosDBSchema;
import sqlancer.cnosdb.ast.CnosDBConcatOperation;
import sqlancer.cnosdb.ast.CnosDBConstant;
import sqlancer.cnosdb.ast.CnosDBExpression;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true) 
public class CnosDBConcatOperation_ESTest extends CnosDBConcatOperation_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      CnosDBConstant.StringConstant cnosDBConstant_StringConstant0 = new CnosDBConstant.StringConstant("");
      CnosDBConcatOperation cnosDBConcatOperation0 = new CnosDBConcatOperation(cnosDBConstant_StringConstant0, cnosDBConstant_StringConstant0);
      String string0 = cnosDBConcatOperation0.getOperatorRepresentation();
      assertEquals("||", string0);
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      CnosDBConcatOperation cnosDBConcatOperation0 = new CnosDBConcatOperation((CnosDBExpression) null, (CnosDBExpression) null);
      CnosDBSchema.CnosDBDataType cnosDBSchema_CnosDBDataType0 = cnosDBConcatOperation0.getExpressionType();
      assertEquals(CnosDBSchema.CnosDBDataType.STRING, cnosDBSchema_CnosDBDataType0);
  }
}
