/*
 * This file was automatically generated by EvoSuite
 * Thu Apr 10 16:27:12 GMT 2025
 */

package sqlancer.citus.oracle.tlp;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;
import sqlancer.citus.CitusGlobalState;
import sqlancer.citus.oracle.tlp.CitusTLPHavingOracle;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true) 
public class CitusTLPHavingOracle_ESTest extends CitusTLPHavingOracle_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      CitusGlobalState citusGlobalState0 = new CitusGlobalState();
      CitusTLPHavingOracle citusTLPHavingOracle0 = new CitusTLPHavingOracle(citusGlobalState0);
      // Undeclared exception!
      try { 
        citusTLPHavingOracle0.check();
        fail("Expecting exception: AssertionError");
      
      } catch(AssertionError e) {
         //
         // null
         //
      }
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      CitusTLPHavingOracle citusTLPHavingOracle0 = new CitusTLPHavingOracle((CitusGlobalState) null);
      // Undeclared exception!
      try { 
        citusTLPHavingOracle0.check();
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("sqlancer.citus.oracle.tlp.CitusTLPHavingOracle", e);
      }
  }
}
