/**
 * Scaffolding file used to store all the setups needed to run 
 * tests automatically generated by EvoSuite
 * Sun Apr 13 13:28:28 GMT 2025
 */

package sqlancer.clickhouse;

import org.evosuite.runtime.annotation.EvoSuiteClassExclude;
import org.junit.BeforeClass;
import org.junit.Before;
import org.junit.After;
import org.junit.AfterClass;
import org.evosuite.runtime.sandbox.Sandbox;
import org.evosuite.runtime.sandbox.Sandbox.SandboxMode;

@EvoSuiteClassExclude
public class ClickHouseOracleFactory_ESTest_scaffolding {

  @org.junit.Rule
  public org.evosuite.runtime.vnet.NonFunctionalRequirementRule nfr = new org.evosuite.runtime.vnet.NonFunctionalRequirementRule();

  private static final java.util.Properties defaultProperties = (java.util.Properties) java.lang.System.getProperties().clone(); 

  private org.evosuite.runtime.thread.ThreadStopper threadStopper =  new org.evosuite.runtime.thread.ThreadStopper (org.evosuite.runtime.thread.KillSwitchHandler.getInstance(), 3000);


  @BeforeClass
  public static void initEvoSuiteFramework() { 
    org.evosuite.runtime.RuntimeSettings.className = "sqlancer.clickhouse.ClickHouseOracleFactory"; 
    org.evosuite.runtime.GuiSupport.initialize(); 
    org.evosuite.runtime.RuntimeSettings.maxNumberOfThreads = 100; 
    org.evosuite.runtime.RuntimeSettings.maxNumberOfIterationsPerLoop = 10000; 
    org.evosuite.runtime.RuntimeSettings.mockSystemIn = true; 
    org.evosuite.runtime.RuntimeSettings.sandboxMode = org.evosuite.runtime.sandbox.Sandbox.SandboxMode.RECOMMENDED; 
    org.evosuite.runtime.sandbox.Sandbox.initializeSecurityManagerForSUT(); 
    org.evosuite.runtime.classhandling.JDKClassResetter.init();
    setSystemProperties();
    initializeClasses();
    org.evosuite.runtime.Runtime.getInstance().resetRuntime(); 
  } 

  @AfterClass
  public static void clearEvoSuiteFramework(){ 
    Sandbox.resetDefaultSecurityManager(); 
    java.lang.System.setProperties((java.util.Properties) defaultProperties.clone()); 
  } 

  @Before
  public void initTestCase(){ 
    threadStopper.storeCurrentThreads();
    threadStopper.startRecordingTime();
    org.evosuite.runtime.jvm.ShutdownHookHandler.getInstance().initHandler(); 
    org.evosuite.runtime.sandbox.Sandbox.goingToExecuteSUTCode(); 
    setSystemProperties(); 
    org.evosuite.runtime.GuiSupport.setHeadless(); 
    org.evosuite.runtime.Runtime.getInstance().resetRuntime(); 
    org.evosuite.runtime.agent.InstrumentingAgent.activate(); 
  } 

  @After
  public void doneWithTestCase(){ 
    threadStopper.killAndJoinClientThreads();
    org.evosuite.runtime.jvm.ShutdownHookHandler.getInstance().safeExecuteAddedHooks(); 
    org.evosuite.runtime.classhandling.JDKClassResetter.reset(); 
    resetClasses(); 
    org.evosuite.runtime.sandbox.Sandbox.doneWithExecutingSUTCode(); 
    org.evosuite.runtime.agent.InstrumentingAgent.deactivate(); 
    org.evosuite.runtime.GuiSupport.restoreHeadlessMode(); 
  } 

  public static void setSystemProperties() {
 
    java.lang.System.setProperties((java.util.Properties) defaultProperties.clone()); 
    java.lang.System.setProperty("user.dir", "E:\\Y2S2\\CS3213\\Sqlancer_original"); 
    java.lang.System.setProperty("java.io.tmpdir", "C:\\Users\\hp\\AppData\\Local\\Temp\\"); 
  }

  private static void initializeClasses() {
    org.evosuite.runtime.classhandling.ClassStateSupport.initializeClasses(ClickHouseOracleFactory_ESTest_scaffolding.class.getClassLoader() ,
      "sqlancer.AbstractAction",
      "sqlancer.clickhouse.oracle.tlp.ClickHouseTLPAggregateOracle",
      "sqlancer.clickhouse.ClickHouseOptions",
      "sqlancer.common.oracle.NoRECOracle",
      "sqlancer.common.gen.NoRECGenerator",
      "sqlancer.OracleFactory",
      "sqlancer.StatementExecutor",
      "sqlancer.SQLProviderAdapter",
      "sqlancer.clickhouse.ClickHouseSchema",
      "sqlancer.common.gen.ExpressionGenerator",
      "sqlancer.clickhouse.ast.ClickHouseTableReference",
      "sqlancer.Main$StateLogger",
      "sqlancer.common.visitor.UnaryOperation",
      "sqlancer.common.query.ExpectedErrors",
      "sqlancer.clickhouse.ast.ClickHouseConstant",
      "sqlancer.GlobalState",
      "sqlancer.common.ast.newast.Select",
      "sqlancer.clickhouse.ast.ClickHouseBinaryArithmeticOperation",
      "sqlancer.clickhouse.ast.ClickHouseExpression",
      "sqlancer.common.schema.AbstractSchema",
      "sqlancer.common.query.ExpectedErrors$ExpectedErrorsBuilder",
      "sqlancer.clickhouse.ast.ClickHouseBinaryLogicalOperation",
      "sqlancer.clickhouse.ast.ClickHouseColumnReference",
      "sqlancer.clickhouse.ast.ClickHouseUnaryPrefixOperation",
      "sqlancer.clickhouse.ClickHouseErrors",
      "sqlancer.DatabaseProvider",
      "sqlancer.clickhouse.ClickHouseProvider$Action",
      "sqlancer.common.gen.PartitionGenerator",
      "sqlancer.Main$QueryManager",
      "sqlancer.clickhouse.ast.ClickHouseUnaryPostfixOperation",
      "sqlancer.clickhouse.oracle.tlp.ClickHouseTLPGroupByOracle",
      "sqlancer.clickhouse.ast.ClickHouseBinaryFunctionOperation",
      "sqlancer.common.gen.TypedExpressionGenerator",
      "sqlancer.clickhouse.oracle.tlp.ClickHouseTLPBase",
      "sqlancer.ProviderAdapter",
      "sqlancer.common.query.Query",
      "sqlancer.clickhouse.ast.ClickHouseUnaryFunctionOperation",
      "sqlancer.common.oracle.TLPWhereOracle",
      "sqlancer.SQLancerDBConnection",
      "sqlancer.MainOptions",
      "sqlancer.Randomly",
      "sqlancer.clickhouse.oracle.tlp.ClickHouseTLPDistinctOracle",
      "sqlancer.common.visitor.BinaryOperation",
      "sqlancer.clickhouse.ClickHouseProvider$ClickHouseGlobalState",
      "sqlancer.common.gen.TLPWhereGenerator",
      "sqlancer.common.oracle.TestOracle",
      "sqlancer.common.query.SQLancerResultSet",
      "sqlancer.common.ast.newast.Expression",
      "sqlancer.SQLGlobalState",
      "sqlancer.StateToReproduce",
      "sqlancer.clickhouse.ClickHouseOracleFactory",
      "sqlancer.clickhouse.ClickHouseProvider",
      "sqlancer.clickhouse.oracle.tlp.ClickHouseTLPHavingOracle",
      "sqlancer.clickhouse.ast.ClickHouseSelect",
      "sqlancer.clickhouse.gen.ClickHouseExpressionGenerator",
      "sqlancer.clickhouse.ast.ClickHouseAggregate",
      "sqlancer.clickhouse.ClickHouseOracleFactory$4",
      "sqlancer.DBMSSpecificOptions",
      "sqlancer.clickhouse.ast.ClickHouseBinaryComparisonOperation",
      "sqlancer.clickhouse.ClickHouseOracleFactory$3",
      "sqlancer.clickhouse.ClickHouseOracleFactory$2",
      "sqlancer.clickhouse.ClickHouseOracleFactory$1",
      "sqlancer.common.log.Loggable",
      "sqlancer.IgnoreMeException",
      "sqlancer.clickhouse.ClickHouseOracleFactory$6",
      "sqlancer.clickhouse.ClickHouseOracleFactory$5",
      "sqlancer.common.oracle.TernaryLogicPartitioningOracleBase",
      "sqlancer.Reproducer"
    );
  } 

  private static void resetClasses() {
    org.evosuite.runtime.classhandling.ClassResetter.getInstance().setClassLoader(ClickHouseOracleFactory_ESTest_scaffolding.class.getClassLoader()); 

    org.evosuite.runtime.classhandling.ClassStateSupport.resetClasses(
      "sqlancer.clickhouse.ClickHouseOracleFactory",
      "sqlancer.GlobalState",
      "sqlancer.SQLGlobalState",
      "sqlancer.clickhouse.ClickHouseProvider$ClickHouseGlobalState",
      "sqlancer.common.oracle.TernaryLogicPartitioningOracleBase",
      "sqlancer.clickhouse.oracle.tlp.ClickHouseTLPBase",
      "sqlancer.clickhouse.oracle.tlp.ClickHouseTLPGroupByOracle",
      "sqlancer.common.query.ExpectedErrors",
      "sqlancer.clickhouse.ClickHouseErrors",
      "sqlancer.clickhouse.oracle.tlp.ClickHouseTLPAggregateOracle",
      "sqlancer.common.gen.TypedExpressionGenerator",
      "sqlancer.clickhouse.gen.ClickHouseExpressionGenerator",
      "sqlancer.common.query.ExpectedErrors$ExpectedErrorsBuilder",
      "sqlancer.common.oracle.TLPWhereOracle",
      "sqlancer.common.query.Query",
      "sqlancer.common.query.SQLQueryAdapter",
      "sqlancer.materialize.MaterializeGlobalState",
      "sqlancer.common.oracle.NoRECOracle",
      "sqlancer.common.query.SQLQueryResultCheckAdapter",
      "sqlancer.clickhouse.oracle.tlp.ClickHouseTLPHavingOracle",
      "sqlancer.clickhouse.oracle.tlp.ClickHouseTLPDistinctOracle",
      "sqlancer.postgres.PostgresGlobalState",
      "sqlancer.citus.CitusGlobalState",
      "sqlancer.presto.PrestoGlobalState",
      "sqlancer.cockroachdb.CockroachDBProvider$CockroachDBGlobalState"
    );
  }
}
