/*
 * This file was automatically generated by EvoSuite
 * Mon Apr 14 12:01:53 GMT 2025
 */

package sqlancer.presto;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;
import sqlancer.presto.PrestoGlobalState;
import sqlancer.presto.PrestoProvider;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true) 
public class PrestoProvider_ESTest extends PrestoProvider_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      PrestoProvider prestoProvider0 = new PrestoProvider();
      try { 
        prestoProvider0.generateDatabase((PrestoGlobalState) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("sqlancer.presto.gen.PrestoTableGenerator", e);
      }
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      PrestoProvider prestoProvider0 = new PrestoProvider();
      PrestoGlobalState prestoGlobalState0 = new PrestoGlobalState();
      // Undeclared exception!
      try { 
        prestoProvider0.createDatabase(prestoGlobalState0);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("sqlancer.presto.PrestoProvider", e);
      }
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      PrestoProvider prestoProvider0 = new PrestoProvider();
      PrestoGlobalState prestoGlobalState0 = new PrestoGlobalState();
      // Undeclared exception!
      try { 
        prestoProvider0.generateDatabase(prestoGlobalState0);
        fail("Expecting exception: AssertionError");
      
      } catch(AssertionError e) {
         //
         // null
         //
      }
  }

  @Test(timeout = 4000)
  public void test3()  throws Throwable  {
      PrestoGlobalState prestoGlobalState0 = new PrestoGlobalState();
      PrestoProvider.Action prestoProvider_Action0 = PrestoProvider.Action.INSERT;
      // Undeclared exception!
      try { 
        prestoProvider_Action0.getQuery(prestoGlobalState0);
        fail("Expecting exception: AssertionError");
      
      } catch(AssertionError e) {
         //
         // null
         //
      }
  }

  @Test(timeout = 4000)
  public void test4()  throws Throwable  {
      PrestoProvider prestoProvider0 = new PrestoProvider();
      String string0 = prestoProvider0.getDBMSName();
      assertEquals("presto", string0);
  }
}
