/*
 * This file was automatically generated by EvoSuite
 * Mon Apr 14 05:06:53 GMT 2025
 */

package sqlancer.cockroachdb.oracle;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;
import sqlancer.cockroachdb.CockroachDBProvider;
import sqlancer.cockroachdb.oracle.CockroachDBCERTOracle;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true) 
public class CockroachDBCERTOracle_ESTest extends CockroachDBCERTOracle_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      CockroachDBProvider.CockroachDBGlobalState cockroachDBProvider_CockroachDBGlobalState0 = new CockroachDBProvider.CockroachDBGlobalState();
      CockroachDBCERTOracle cockroachDBCERTOracle0 = new CockroachDBCERTOracle(cockroachDBProvider_CockroachDBGlobalState0);
      // Undeclared exception!
      try { 
        cockroachDBCERTOracle0.mutateWhere();
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("sqlancer.cockroachdb.oracle.CockroachDBCERTOracle", e);
      }
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      CockroachDBProvider.CockroachDBGlobalState cockroachDBProvider_CockroachDBGlobalState0 = new CockroachDBProvider.CockroachDBGlobalState();
      CockroachDBCERTOracle cockroachDBCERTOracle0 = new CockroachDBCERTOracle(cockroachDBProvider_CockroachDBGlobalState0);
      // Undeclared exception!
      try { 
        cockroachDBCERTOracle0.mutateOr();
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("sqlancer.cockroachdb.oracle.CockroachDBCERTOracle", e);
      }
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      CockroachDBProvider.CockroachDBGlobalState cockroachDBProvider_CockroachDBGlobalState0 = new CockroachDBProvider.CockroachDBGlobalState();
      CockroachDBCERTOracle cockroachDBCERTOracle0 = new CockroachDBCERTOracle(cockroachDBProvider_CockroachDBGlobalState0);
      // Undeclared exception!
      try { 
        cockroachDBCERTOracle0.mutateLimit();
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("sqlancer.cockroachdb.oracle.CockroachDBCERTOracle", e);
      }
  }

  @Test(timeout = 4000)
  public void test3()  throws Throwable  {
      CockroachDBCERTOracle cockroachDBCERTOracle0 = new CockroachDBCERTOracle((CockroachDBProvider.CockroachDBGlobalState) null);
      // Undeclared exception!
      try { 
        cockroachDBCERTOracle0.mutateJoin();
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("sqlancer.cockroachdb.oracle.CockroachDBCERTOracle", e);
      }
  }

  @Test(timeout = 4000)
  public void test4()  throws Throwable  {
      CockroachDBProvider.CockroachDBGlobalState cockroachDBProvider_CockroachDBGlobalState0 = new CockroachDBProvider.CockroachDBGlobalState();
      CockroachDBCERTOracle cockroachDBCERTOracle0 = new CockroachDBCERTOracle(cockroachDBProvider_CockroachDBGlobalState0);
      // Undeclared exception!
      try { 
        cockroachDBCERTOracle0.mutateHaving();
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("sqlancer.cockroachdb.oracle.CockroachDBCERTOracle", e);
      }
  }

  @Test(timeout = 4000)
  public void test5()  throws Throwable  {
      CockroachDBProvider.CockroachDBGlobalState cockroachDBProvider_CockroachDBGlobalState0 = new CockroachDBProvider.CockroachDBGlobalState();
      CockroachDBCERTOracle cockroachDBCERTOracle0 = new CockroachDBCERTOracle(cockroachDBProvider_CockroachDBGlobalState0);
      // Undeclared exception!
      try { 
        cockroachDBCERTOracle0.mutateGroupBy();
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("sqlancer.cockroachdb.oracle.CockroachDBCERTOracle", e);
      }
  }

  @Test(timeout = 4000)
  public void test6()  throws Throwable  {
      CockroachDBProvider.CockroachDBGlobalState cockroachDBProvider_CockroachDBGlobalState0 = new CockroachDBProvider.CockroachDBGlobalState();
      CockroachDBCERTOracle cockroachDBCERTOracle0 = new CockroachDBCERTOracle(cockroachDBProvider_CockroachDBGlobalState0);
      // Undeclared exception!
      try { 
        cockroachDBCERTOracle0.mutateDistinct();
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("sqlancer.cockroachdb.oracle.CockroachDBCERTOracle", e);
      }
  }

  @Test(timeout = 4000)
  public void test7()  throws Throwable  {
      CockroachDBProvider.CockroachDBGlobalState cockroachDBProvider_CockroachDBGlobalState0 = new CockroachDBProvider.CockroachDBGlobalState();
      CockroachDBCERTOracle cockroachDBCERTOracle0 = new CockroachDBCERTOracle(cockroachDBProvider_CockroachDBGlobalState0);
      // Undeclared exception!
      try { 
        cockroachDBCERTOracle0.mutateAnd();
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("sqlancer.cockroachdb.oracle.CockroachDBCERTOracle", e);
      }
  }

  @Test(timeout = 4000)
  public void test8()  throws Throwable  {
      CockroachDBProvider.CockroachDBGlobalState cockroachDBProvider_CockroachDBGlobalState0 = new CockroachDBProvider.CockroachDBGlobalState();
      CockroachDBCERTOracle cockroachDBCERTOracle0 = new CockroachDBCERTOracle(cockroachDBProvider_CockroachDBGlobalState0);
      // Undeclared exception!
      try { 
        cockroachDBCERTOracle0.check();
        fail("Expecting exception: AssertionError");
      
      } catch(AssertionError e) {
         //
         // null
         //
      }
  }

  @Test(timeout = 4000)
  public void test9()  throws Throwable  {
      CockroachDBCERTOracle cockroachDBCERTOracle0 = new CockroachDBCERTOracle((CockroachDBProvider.CockroachDBGlobalState) null);
      // Undeclared exception!
      try { 
        cockroachDBCERTOracle0.check();
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("sqlancer.cockroachdb.oracle.CockroachDBCERTOracle", e);
      }
  }
}
