/**
 * Scaffolding file used to store all the setups needed to run 
 * tests automatically generated by EvoSuite
 * Thu Apr 10 15:55:17 GMT 2025
 */

package sqlancer.citus;

import org.evosuite.runtime.annotation.EvoSuiteClassExclude;
import org.junit.BeforeClass;
import org.junit.Before;
import org.junit.After;
import org.junit.AfterClass;
import org.evosuite.runtime.sandbox.Sandbox;
import org.evosuite.runtime.sandbox.Sandbox.SandboxMode;

@EvoSuiteClassExclude
public class CitusOptions_ESTest_scaffolding {

  @org.junit.Rule
  public org.evosuite.runtime.vnet.NonFunctionalRequirementRule nfr = new org.evosuite.runtime.vnet.NonFunctionalRequirementRule();

  private static final java.util.Properties defaultProperties = (java.util.Properties) java.lang.System.getProperties().clone(); 

  private org.evosuite.runtime.thread.ThreadStopper threadStopper =  new org.evosuite.runtime.thread.ThreadStopper (org.evosuite.runtime.thread.KillSwitchHandler.getInstance(), 3000);


  @BeforeClass
  public static void initEvoSuiteFramework() { 
    org.evosuite.runtime.RuntimeSettings.className = "sqlancer.citus.CitusOptions"; 
    org.evosuite.runtime.GuiSupport.initialize(); 
    org.evosuite.runtime.RuntimeSettings.maxNumberOfThreads = 100; 
    org.evosuite.runtime.RuntimeSettings.maxNumberOfIterationsPerLoop = 10000; 
    org.evosuite.runtime.RuntimeSettings.mockSystemIn = true; 
    org.evosuite.runtime.RuntimeSettings.sandboxMode = org.evosuite.runtime.sandbox.Sandbox.SandboxMode.RECOMMENDED; 
    org.evosuite.runtime.sandbox.Sandbox.initializeSecurityManagerForSUT(); 
    org.evosuite.runtime.classhandling.JDKClassResetter.init();
    setSystemProperties();
    initializeClasses();
    org.evosuite.runtime.Runtime.getInstance().resetRuntime(); 
  } 

  @AfterClass
  public static void clearEvoSuiteFramework(){ 
    Sandbox.resetDefaultSecurityManager(); 
    java.lang.System.setProperties((java.util.Properties) defaultProperties.clone()); 
  } 

  @Before
  public void initTestCase(){ 
    threadStopper.storeCurrentThreads();
    threadStopper.startRecordingTime();
    org.evosuite.runtime.jvm.ShutdownHookHandler.getInstance().initHandler(); 
    org.evosuite.runtime.sandbox.Sandbox.goingToExecuteSUTCode(); 
    setSystemProperties(); 
    org.evosuite.runtime.GuiSupport.setHeadless(); 
    org.evosuite.runtime.Runtime.getInstance().resetRuntime(); 
    org.evosuite.runtime.agent.InstrumentingAgent.activate(); 
  } 

  @After
  public void doneWithTestCase(){ 
    threadStopper.killAndJoinClientThreads();
    org.evosuite.runtime.jvm.ShutdownHookHandler.getInstance().safeExecuteAddedHooks(); 
    org.evosuite.runtime.classhandling.JDKClassResetter.reset(); 
    resetClasses(); 
    org.evosuite.runtime.sandbox.Sandbox.doneWithExecutingSUTCode(); 
    org.evosuite.runtime.agent.InstrumentingAgent.deactivate(); 
    org.evosuite.runtime.GuiSupport.restoreHeadlessMode(); 
  } 

  public static void setSystemProperties() {
 
    java.lang.System.setProperties((java.util.Properties) defaultProperties.clone()); 
    java.lang.System.setProperty("user.dir", "E:\\Y2S2\\CS3213\\Sqlancer_original"); 
    java.lang.System.setProperty("java.io.tmpdir", "C:\\Users\\hp\\AppData\\Local\\Temp\\"); 
  }

  private static void initializeClasses() {
    org.evosuite.runtime.classhandling.ClassStateSupport.initializeClasses(CitusOptions_ESTest_scaffolding.class.getClassLoader() ,
      "sqlancer.postgres.PostgresOracleFactory$7",
      "sqlancer.postgres.PostgresOracleFactory$5",
      "sqlancer.postgres.PostgresOracleFactory$6",
      "sqlancer.common.gen.NoRECGenerator",
      "sqlancer.OracleFactory",
      "sqlancer.citus.CitusOptions",
      "sqlancer.postgres.PostgresOracleFactory$3",
      "sqlancer.postgres.PostgresOracleFactory$4",
      "sqlancer.postgres.PostgresOracleFactory$1",
      "sqlancer.postgres.PostgresOracleFactory$2",
      "sqlancer.common.oracle.TestOracle",
      "sqlancer.common.gen.TLPWhereGenerator",
      "sqlancer.common.gen.CERTGenerator",
      "sqlancer.citus.CitusOracleFactory",
      "sqlancer.SQLGlobalState",
      "sqlancer.postgres.PostgresGlobalState",
      "sqlancer.GlobalState",
      "sqlancer.postgres.PostgresOptions",
      "sqlancer.citus.CitusOracleFactory$5",
      "sqlancer.citus.CitusOracleFactory$2",
      "sqlancer.citus.CitusOracleFactory$1",
      "sqlancer.citus.CitusOracleFactory$4",
      "sqlancer.citus.CitusOracleFactory$3",
      "sqlancer.DBMSSpecificOptions",
      "sqlancer.common.gen.PartitionGenerator",
      "sqlancer.postgres.PostgresOracleFactory",
      "sqlancer.citus.CitusGlobalState"
    );
  } 

  private static void resetClasses() {
    org.evosuite.runtime.classhandling.ClassResetter.getInstance().setClassLoader(CitusOptions_ESTest_scaffolding.class.getClassLoader()); 

    org.evosuite.runtime.classhandling.ClassStateSupport.resetClasses(
      "sqlancer.postgres.PostgresOptions",
      "sqlancer.citus.CitusOptions",
      "sqlancer.citus.CitusOracleFactory",
      "sqlancer.postgres.PostgresOracleFactory"
    );
  }
}
