/*
 * This file was automatically generated by EvoSuite
 * Thu Apr 10 16:02:16 GMT 2025
 */

package sqlancer.citus;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;
import sqlancer.citus.CitusGlobalState;
import sqlancer.citus.CitusOracleFactory;
import sqlancer.common.oracle.TestOracle;
import sqlancer.postgres.PostgresGlobalState;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true) 
public class CitusOracleFactory_ESTest extends CitusOracleFactory_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      CitusOracleFactory citusOracleFactory0 = CitusOracleFactory.HAVING;
      CitusGlobalState citusGlobalState0 = new CitusGlobalState();
      TestOracle<PostgresGlobalState> testOracle0 = citusOracleFactory0.create(citusGlobalState0);
      assertNotNull(testOracle0);
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      CitusOracleFactory citusOracleFactory0 = CitusOracleFactory.NOREC;
      CitusGlobalState citusGlobalState0 = new CitusGlobalState();
      try { 
        citusOracleFactory0.create(citusGlobalState0);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("sqlancer.postgres.gen.PostgresExpressionGenerator", e);
      }
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      CitusOracleFactory citusOracleFactory0 = CitusOracleFactory.PQS;
      CitusGlobalState citusGlobalState0 = new CitusGlobalState();
      TestOracle<PostgresGlobalState> testOracle0 = citusOracleFactory0.create(citusGlobalState0);
      assertNotNull(testOracle0);
  }

  @Test(timeout = 4000)
  public void test3()  throws Throwable  {
      CitusOracleFactory citusOracleFactory0 = CitusOracleFactory.QUERY_PARTITIONING;
      CitusGlobalState citusGlobalState0 = new CitusGlobalState();
      try { 
        citusOracleFactory0.create(citusGlobalState0);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("sqlancer.postgres.gen.PostgresExpressionGenerator", e);
      }
  }
}
