/**
 * Scaffolding file used to store all the setups needed to run 
 * tests automatically generated by EvoSuite
 * Thu Apr 10 16:02:16 GMT 2025
 */

package sqlancer.citus;

import org.evosuite.runtime.annotation.EvoSuiteClassExclude;
import org.junit.BeforeClass;
import org.junit.Before;
import org.junit.After;
import org.junit.AfterClass;
import org.evosuite.runtime.sandbox.Sandbox;
import org.evosuite.runtime.sandbox.Sandbox.SandboxMode;

@EvoSuiteClassExclude
public class CitusOracleFactory_ESTest_scaffolding {

  @org.junit.Rule
  public org.evosuite.runtime.vnet.NonFunctionalRequirementRule nfr = new org.evosuite.runtime.vnet.NonFunctionalRequirementRule();

  private static final java.util.Properties defaultProperties = (java.util.Properties) java.lang.System.getProperties().clone(); 

  private org.evosuite.runtime.thread.ThreadStopper threadStopper =  new org.evosuite.runtime.thread.ThreadStopper (org.evosuite.runtime.thread.KillSwitchHandler.getInstance(), 3000);


  @BeforeClass
  public static void initEvoSuiteFramework() { 
    org.evosuite.runtime.RuntimeSettings.className = "sqlancer.citus.CitusOracleFactory"; 
    org.evosuite.runtime.GuiSupport.initialize(); 
    org.evosuite.runtime.RuntimeSettings.maxNumberOfThreads = 100; 
    org.evosuite.runtime.RuntimeSettings.maxNumberOfIterationsPerLoop = 10000; 
    org.evosuite.runtime.RuntimeSettings.mockSystemIn = true; 
    org.evosuite.runtime.RuntimeSettings.sandboxMode = org.evosuite.runtime.sandbox.Sandbox.SandboxMode.RECOMMENDED; 
    org.evosuite.runtime.sandbox.Sandbox.initializeSecurityManagerForSUT(); 
    org.evosuite.runtime.classhandling.JDKClassResetter.init();
    setSystemProperties();
    initializeClasses();
    org.evosuite.runtime.Runtime.getInstance().resetRuntime(); 
  } 

  @AfterClass
  public static void clearEvoSuiteFramework(){ 
    Sandbox.resetDefaultSecurityManager(); 
    java.lang.System.setProperties((java.util.Properties) defaultProperties.clone()); 
  } 

  @Before
  public void initTestCase(){ 
    threadStopper.storeCurrentThreads();
    threadStopper.startRecordingTime();
    org.evosuite.runtime.jvm.ShutdownHookHandler.getInstance().initHandler(); 
    org.evosuite.runtime.sandbox.Sandbox.goingToExecuteSUTCode(); 
    setSystemProperties(); 
    org.evosuite.runtime.GuiSupport.setHeadless(); 
    org.evosuite.runtime.Runtime.getInstance().resetRuntime(); 
    org.evosuite.runtime.agent.InstrumentingAgent.activate(); 
  } 

  @After
  public void doneWithTestCase(){ 
    threadStopper.killAndJoinClientThreads();
    org.evosuite.runtime.jvm.ShutdownHookHandler.getInstance().safeExecuteAddedHooks(); 
    org.evosuite.runtime.classhandling.JDKClassResetter.reset(); 
    resetClasses(); 
    org.evosuite.runtime.sandbox.Sandbox.doneWithExecutingSUTCode(); 
    org.evosuite.runtime.agent.InstrumentingAgent.deactivate(); 
    org.evosuite.runtime.GuiSupport.restoreHeadlessMode(); 
  } 

  public static void setSystemProperties() {
 
    java.lang.System.setProperties((java.util.Properties) defaultProperties.clone()); 
    java.lang.System.setProperty("user.dir", "E:\\Y2S2\\CS3213\\Sqlancer_original"); 
    java.lang.System.setProperty("java.io.tmpdir", "C:\\Users\\hp\\AppData\\Local\\Temp\\"); 
  }

  private static void initializeClasses() {
    org.evosuite.runtime.classhandling.ClassStateSupport.initializeClasses(CitusOracleFactory_ESTest_scaffolding.class.getClassLoader() ,
      "sqlancer.postgres.ast.PostgresBinaryComparisonOperation",
      "sqlancer.postgres.PostgresSchema$PostgresTable",
      "sqlancer.common.gen.NoRECGenerator",
      "sqlancer.OracleFactory",
      "sqlancer.common.gen.ExpressionGenerator",
      "sqlancer.postgres.PostgresSchema$PostgresRowValue",
      "sqlancer.postgres.gen.PostgresCommon",
      "sqlancer.citus.gen.CitusCommon",
      "sqlancer.Main$StateLogger",
      "sqlancer.postgres.PostgresGlobalState",
      "sqlancer.citus.oracle.tlp.CitusTLPHavingOracle",
      "sqlancer.citus.oracle.tlp.CitusTLPAggregateOracle",
      "sqlancer.citus.CitusSchema$CitusTable",
      "sqlancer.common.schema.AbstractTable",
      "sqlancer.common.query.ExpectedErrors",
      "sqlancer.GlobalState",
      "sqlancer.citus.CitusOracleFactory$5",
      "sqlancer.citus.CitusBugs",
      "sqlancer.common.ast.newast.Select",
      "sqlancer.citus.CitusOracleFactory$2",
      "sqlancer.citus.CitusOracleFactory$1",
      "sqlancer.citus.CitusOracleFactory$4",
      "sqlancer.common.schema.AbstractSchema",
      "sqlancer.postgres.PostgresSchema",
      "sqlancer.citus.CitusOracleFactory$3",
      "sqlancer.common.gen.PartitionGenerator",
      "sqlancer.Main$QueryManager",
      "sqlancer.common.schema.AbstractRelationalTable",
      "sqlancer.postgres.ast.PostgresExpression",
      "sqlancer.common.query.Query",
      "sqlancer.common.oracle.PivotedQuerySynthesisBase",
      "sqlancer.postgres.oracle.tlp.PostgresTLPAggregateOracle",
      "sqlancer.SQLancerDBConnection",
      "sqlancer.MainOptions",
      "sqlancer.Randomly",
      "sqlancer.common.ast.BinaryNode",
      "sqlancer.common.ast.BinaryOperatorNode",
      "sqlancer.common.visitor.BinaryOperation",
      "sqlancer.postgres.ast.PostgresBinaryLogicalOperation",
      "sqlancer.common.oracle.TestOracle",
      "sqlancer.common.gen.TLPWhereGenerator",
      "sqlancer.common.query.SQLancerResultSet",
      "sqlancer.common.gen.CERTGenerator",
      "sqlancer.common.query.SQLQueryAdapter",
      "sqlancer.postgres.oracle.tlp.PostgresTLPHavingOracle",
      "sqlancer.citus.CitusOracleFactory",
      "sqlancer.common.ast.newast.Expression",
      "sqlancer.SQLGlobalState",
      "sqlancer.StateToReproduce",
      "sqlancer.SQLConnection",
      "sqlancer.citus.oracle.tlp.CitusTLPBase",
      "sqlancer.postgres.oracle.tlp.PostgresTLPBase",
      "sqlancer.DBMSSpecificOptions",
      "sqlancer.citus.CitusSchema",
      "sqlancer.common.log.Loggable",
      "sqlancer.IgnoreMeException",
      "sqlancer.common.schema.AbstractRowValue",
      "sqlancer.citus.CitusGlobalState",
      "sqlancer.postgres.oracle.PostgresPivotedQuerySynthesisOracle",
      "sqlancer.postgres.gen.PostgresExpressionGenerator",
      "sqlancer.common.oracle.TernaryLogicPartitioningOracleBase",
      "sqlancer.Reproducer"
    );
  } 

  private static void resetClasses() {
    org.evosuite.runtime.classhandling.ClassResetter.getInstance().setClassLoader(CitusOracleFactory_ESTest_scaffolding.class.getClassLoader()); 

    org.evosuite.runtime.classhandling.ClassStateSupport.resetClasses(
      "sqlancer.citus.CitusOracleFactory",
      "sqlancer.GlobalState",
      "sqlancer.SQLGlobalState",
      "sqlancer.postgres.PostgresGlobalState",
      "sqlancer.citus.CitusGlobalState",
      "sqlancer.common.oracle.PivotedQuerySynthesisBase",
      "sqlancer.postgres.oracle.PostgresPivotedQuerySynthesisOracle",
      "sqlancer.common.query.ExpectedErrors",
      "sqlancer.postgres.gen.PostgresCommon",
      "sqlancer.common.query.Query",
      "sqlancer.common.query.SQLQueryAdapter",
      "sqlancer.materialize.MaterializeGlobalState",
      "sqlancer.common.query.ExpectedErrors$ExpectedErrorsBuilder",
      "sqlancer.postgres.gen.PostgresExpressionGenerator",
      "sqlancer.common.oracle.TernaryLogicPartitioningOracleBase",
      "sqlancer.postgres.oracle.tlp.PostgresTLPBase",
      "sqlancer.postgres.oracle.tlp.PostgresTLPHavingOracle",
      "sqlancer.citus.oracle.tlp.CitusTLPHavingOracle",
      "sqlancer.citus.gen.CitusCommon",
      "sqlancer.citus.CitusBugs",
      "sqlancer.citus.oracle.tlp.CitusTLPBase",
      "sqlancer.common.query.SQLQueryResultCheckAdapter"
    );
  }
}
