/*
 * This file was automatically generated by EvoSuite
 * Mon Apr 14 08:14:49 GMT 2025
 */

package sqlancer.databend.ast;

import org.junit.Test;
import static org.junit.Assert.*;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;
import sqlancer.common.ast.newast.NewOrderingTerm;
import sqlancer.databend.ast.DatabendExpression;
import sqlancer.databend.ast.DatabendOrderByTerm;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true) 
public class DatabendOrderByTerm_ESTest extends DatabendOrderByTerm_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      NewOrderingTerm.Ordering newOrderingTerm_Ordering0 = NewOrderingTerm.Ordering.ASC;
      DatabendOrderByTerm databendOrderByTerm0 = new DatabendOrderByTerm((DatabendExpression) null, newOrderingTerm_Ordering0);
      assertEquals(NewOrderingTerm.Ordering.ASC, databendOrderByTerm0.getOrdering());
  }
}
