/*
 * This file was automatically generated by EvoSuite
 * Mon Apr 14 08:44:50 GMT 2025
 */

package sqlancer.databend.ast;

import org.junit.Test;
import static org.junit.Assert.*;
import java.util.List;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;
import sqlancer.databend.ast.DatabendExpression;
import sqlancer.databend.ast.DatabendFunctionOperation;
import sqlancer.databend.ast.DatabendSelect;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true) 
public class DatabendFunctionOperation_ESTest extends DatabendFunctionOperation_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      DatabendSelect databendSelect0 = new DatabendSelect();
      List<DatabendExpression> list0 = databendSelect0.getOrderByClauses();
      DatabendFunctionOperation<Object> databendFunctionOperation0 = new DatabendFunctionOperation<Object>(list0, list0);
  }
}
