/**
 * Scaffolding file used to store all the setups needed to run 
 * tests automatically generated by EvoSuite
 * Mon Apr 14 08:43:27 GMT 2025
 */

package sqlancer.databend.ast;

import org.evosuite.runtime.annotation.EvoSuiteClassExclude;
import org.junit.BeforeClass;
import org.junit.Before;
import org.junit.After;
import org.junit.AfterClass;
import org.evosuite.runtime.sandbox.Sandbox;
import org.evosuite.runtime.sandbox.Sandbox.SandboxMode;

@EvoSuiteClassExclude
public class DatabendBetweenOperation_ESTest_scaffolding {

  @org.junit.Rule
  public org.evosuite.runtime.vnet.NonFunctionalRequirementRule nfr = new org.evosuite.runtime.vnet.NonFunctionalRequirementRule();

  private static final java.util.Properties defaultProperties = (java.util.Properties) java.lang.System.getProperties().clone(); 

  private org.evosuite.runtime.thread.ThreadStopper threadStopper =  new org.evosuite.runtime.thread.ThreadStopper (org.evosuite.runtime.thread.KillSwitchHandler.getInstance(), 3000);


  @BeforeClass
  public static void initEvoSuiteFramework() { 
    org.evosuite.runtime.RuntimeSettings.className = "sqlancer.databend.ast.DatabendBetweenOperation"; 
    org.evosuite.runtime.GuiSupport.initialize(); 
    org.evosuite.runtime.RuntimeSettings.maxNumberOfThreads = 100; 
    org.evosuite.runtime.RuntimeSettings.maxNumberOfIterationsPerLoop = 10000; 
    org.evosuite.runtime.RuntimeSettings.mockSystemIn = true; 
    org.evosuite.runtime.RuntimeSettings.sandboxMode = org.evosuite.runtime.sandbox.Sandbox.SandboxMode.RECOMMENDED; 
    org.evosuite.runtime.sandbox.Sandbox.initializeSecurityManagerForSUT(); 
    org.evosuite.runtime.classhandling.JDKClassResetter.init();
    setSystemProperties();
    initializeClasses();
    org.evosuite.runtime.Runtime.getInstance().resetRuntime(); 
  } 

  @AfterClass
  public static void clearEvoSuiteFramework(){ 
    Sandbox.resetDefaultSecurityManager(); 
    java.lang.System.setProperties((java.util.Properties) defaultProperties.clone()); 
  } 

  @Before
  public void initTestCase(){ 
    threadStopper.storeCurrentThreads();
    threadStopper.startRecordingTime();
    org.evosuite.runtime.jvm.ShutdownHookHandler.getInstance().initHandler(); 
    org.evosuite.runtime.sandbox.Sandbox.goingToExecuteSUTCode(); 
    setSystemProperties(); 
    org.evosuite.runtime.GuiSupport.setHeadless(); 
    org.evosuite.runtime.Runtime.getInstance().resetRuntime(); 
    org.evosuite.runtime.agent.InstrumentingAgent.activate(); 
  } 

  @After
  public void doneWithTestCase(){ 
    threadStopper.killAndJoinClientThreads();
    org.evosuite.runtime.jvm.ShutdownHookHandler.getInstance().safeExecuteAddedHooks(); 
    org.evosuite.runtime.classhandling.JDKClassResetter.reset(); 
    resetClasses(); 
    org.evosuite.runtime.sandbox.Sandbox.doneWithExecutingSUTCode(); 
    org.evosuite.runtime.agent.InstrumentingAgent.deactivate(); 
    org.evosuite.runtime.GuiSupport.restoreHeadlessMode(); 
  } 

  public static void setSystemProperties() {
 
    java.lang.System.setProperties((java.util.Properties) defaultProperties.clone()); 
    java.lang.System.setProperty("user.dir", "E:\\Y2S2\\CS3213\\Sqlancer_original"); 
    java.lang.System.setProperty("java.io.tmpdir", "C:\\Users\\hp\\AppData\\Local\\Temp\\"); 
  }

  private static void initializeClasses() {
    org.evosuite.runtime.classhandling.ClassStateSupport.initializeClasses(DatabendBetweenOperation_ESTest_scaffolding.class.getClassLoader() ,
      "sqlancer.databend.ast.DatabendBinaryLogicalOperation$DatabendBinaryLogicalOperator",
      "sqlancer.databend.ast.DatabendUnaryPostfixOperation",
      "sqlancer.SQLProviderAdapter",
      "sqlancer.databend.DatabendProvider",
      "sqlancer.databend.ast.DatabendConstant$DatabendFloatConstant",
      "sqlancer.common.ast.newast.NewFunctionNode",
      "sqlancer.databend.ast.DatabendBinaryComparisonOperation$DatabendBinaryComparisonOperator$6",
      "sqlancer.databend.ast.DatabendBinaryComparisonOperation$DatabendBinaryComparisonOperator$5",
      "sqlancer.databend.ast.DatabendBinaryComparisonOperation$DatabendBinaryComparisonOperator$4",
      "sqlancer.Randomly$StringGenerationStrategy",
      "sqlancer.databend.ast.DatabendBinaryComparisonOperation$DatabendBinaryComparisonOperator$3",
      "sqlancer.databend.DatabendSchema",
      "sqlancer.databend.ast.DatabendBinaryComparisonOperation$DatabendBinaryComparisonOperator$8",
      "sqlancer.databend.ast.DatabendBinaryComparisonOperation$DatabendBinaryComparisonOperator$7",
      "sqlancer.databend.ast.DatabendBinaryComparisonOperation$DatabendBinaryComparisonOperator$2",
      "sqlancer.common.schema.AbstractTable",
      "sqlancer.databend.ast.DatabendBinaryComparisonOperation$DatabendBinaryComparisonOperator$1",
      "sqlancer.databend.DatabendSchema$DatabendCompositeDataType",
      "sqlancer.databend.ast.DatabendBinaryLogicalOperation",
      "sqlancer.databend.ast.DatabendConstant$DatabendDateConstant",
      "sqlancer.common.schema.AbstractSchema",
      "sqlancer.databend.ast.DatabendBinaryComparisonOperation$DatabendBinaryComparisonOperator",
      "sqlancer.databend.ast.DatabendConstant$DatabendStringConstant",
      "sqlancer.DatabaseProvider",
      "sqlancer.databend.ast.DatabendConstant$DatabendBooleanConstant",
      "sqlancer.databend.ast.DatabendUnaryPrefixOperation$DatabendUnaryPrefixOperator$3",
      "sqlancer.databend.ast.DatabendUnaryPrefixOperation$DatabendUnaryPrefixOperator$2",
      "sqlancer.databend.ast.DatabendUnaryPrefixOperation$DatabendUnaryPrefixOperator$1",
      "sqlancer.ProviderAdapter",
      "sqlancer.common.ast.newast.NewUnaryPostfixOperatorNode",
      "sqlancer.databend.ast.DatabendAlias",
      "sqlancer.common.ast.newast.ColumnReferenceNode",
      "sqlancer.Randomly",
      "sqlancer.common.ast.BinaryNode",
      "sqlancer.common.ast.BinaryOperatorNode",
      "sqlancer.common.visitor.BinaryOperation",
      "sqlancer.common.schema.AbstractTableColumn",
      "sqlancer.databend.ast.DatabendConstant",
      "sqlancer.common.ast.newast.NewAliasNode",
      "sqlancer.databend.ast.DatabendColumnValue",
      "sqlancer.databend.ast.DatabendConstant$DatabendIntConstant",
      "sqlancer.common.ast.newast.Expression",
      "sqlancer.common.ast.BinaryOperatorNode$Operator",
      "sqlancer.Randomly$StringGenerationStrategy$4",
      "sqlancer.Randomly$StringGenerationStrategy$3",
      "sqlancer.Randomly$StringGenerationStrategy$2",
      "sqlancer.common.ast.newast.NewBinaryOperatorNode",
      "sqlancer.Randomly$StringGenerationStrategy$1",
      "sqlancer.databend.ast.DatabendUnaryPostfixOperation$DatabendUnaryPostfixOperator$1",
      "sqlancer.databend.ast.DatabendUnaryPostfixOperation$DatabendUnaryPostfixOperator$2",
      "sqlancer.databend.ast.DatabendBinaryComparisonOperation",
      "sqlancer.databend.ast.DatabendBetweenOperation",
      "sqlancer.databend.DatabendSchema$DatabendColumn",
      "sqlancer.databend.ast.DatabendUnaryPrefixOperation$DatabendUnaryPrefixOperator",
      "sqlancer.databend.DatabendSchema$DatabendDataType",
      "sqlancer.databend.ast.DatabendFunctionOperation",
      "sqlancer.common.ast.newast.NewBetweenOperatorNode",
      "sqlancer.databend.ast.DatabendBinaryLogicalOperation$DatabendBinaryLogicalOperator$2",
      "sqlancer.databend.ast.DatabendBinaryLogicalOperation$DatabendBinaryLogicalOperator$1",
      "sqlancer.databend.ast.DatabendConstant$DatabendNullConstant",
      "sqlancer.common.ast.newast.NewUnaryPrefixOperatorNode",
      "sqlancer.databend.ast.DatabendColumnReference",
      "sqlancer.IgnoreMeException",
      "sqlancer.databend.ast.DatabendConstant$DatabendTimestampConstant",
      "sqlancer.databend.ast.DatabendExpression",
      "sqlancer.databend.ast.DatabendUnaryPostfixOperation$DatabendUnaryPostfixOperator",
      "sqlancer.databend.ast.DatabendUnaryPrefixOperation"
    );
  } 

  private static void resetClasses() {
    org.evosuite.runtime.classhandling.ClassResetter.getInstance().setClassLoader(DatabendBetweenOperation_ESTest_scaffolding.class.getClassLoader()); 

    org.evosuite.runtime.classhandling.ClassStateSupport.resetClasses(
      "sqlancer.common.ast.newast.NewBetweenOperatorNode",
      "sqlancer.databend.ast.DatabendBetweenOperation",
      "sqlancer.databend.ast.DatabendBinaryComparisonOperation$DatabendBinaryComparisonOperator",
      "sqlancer.databend.ast.DatabendBinaryLogicalOperation$DatabendBinaryLogicalOperator",
      "sqlancer.databend.DatabendSchema$DatabendDataType",
      "sqlancer.databend.ast.DatabendConstant",
      "sqlancer.databend.ast.DatabendConstant$DatabendFloatConstant",
      "sqlancer.databend.DatabendSchema$DatabendCompositeDataType",
      "sqlancer.Randomly$StringGenerationStrategy$4",
      "sqlancer.Randomly$StringGenerationStrategy",
      "sqlancer.Randomly",
      "sqlancer.common.ast.newast.NewUnaryPostfixOperatorNode",
      "sqlancer.databend.ast.DatabendCastOperation",
      "sqlancer.databend.ast.DatabendCastOperation$1",
      "sqlancer.databend.ast.DatabendConstant$DatabendStringConstant",
      "sqlancer.databend.ast.DatabendConstant$DatabendTimestampConstant",
      "sqlancer.common.ast.newast.NewBinaryOperatorNode",
      "sqlancer.databend.ast.DatabendBinaryComparisonOperation",
      "sqlancer.databend.ast.DatabendBinaryLogicalOperation",
      "sqlancer.databend.ast.DatabendConstant$DatabendDateConstant",
      "sqlancer.databend.ast.DatabendConstant$DatabendBooleanConstant",
      "sqlancer.common.ast.newast.ColumnReferenceNode",
      "sqlancer.databend.ast.DatabendColumnReference",
      "sqlancer.common.ast.SelectBase",
      "sqlancer.databend.ast.DatabendSelect",
      "sqlancer.common.ast.newast.NewOrderingTerm",
      "sqlancer.databend.ast.DatabendOrderByTerm",
      "sqlancer.databend.ast.DatabendConstant$DatabendIntConstant",
      "sqlancer.databend.ast.DatabendConstant$DatabendNullConstant",
      "sqlancer.common.ast.newast.NewFunctionNode",
      "sqlancer.databend.ast.DatabendFunctionOperation",
      "sqlancer.databend.ast.DatabendUnaryPostfixOperation",
      "sqlancer.common.ast.newast.NewAliasNode",
      "sqlancer.databend.ast.DatabendAlias",
      "sqlancer.common.schema.AbstractTableColumn",
      "sqlancer.databend.DatabendSchema$DatabendColumn",
      "sqlancer.databend.ast.DatabendColumnValue",
      "sqlancer.common.ast.newast.NewUnaryPrefixOperatorNode",
      "sqlancer.databend.ast.DatabendUnaryPrefixOperation",
      "sqlancer.common.schema.AbstractTable",
      "sqlancer.common.schema.AbstractRelationalTable",
      "sqlancer.databend.DatabendSchema$DatabendTable",
      "sqlancer.common.ast.newast.NewPostfixTextNode",
      "sqlancer.databend.ast.DatabendPostFixText",
      "sqlancer.common.ast.newast.TableReferenceNode",
      "sqlancer.databend.ast.DatabendTableReference",
      "sqlancer.databend.ast.DatabendJoin",
      "sqlancer.h2.H2ExpressionGenerator$H2BinaryComparisonOperator",
      "sqlancer.databend.ast.DatabendBinaryOperation",
      "sqlancer.common.ast.newast.NewInOperatorNode",
      "sqlancer.databend.ast.DatabendInOperation",
      "sqlancer.common.ast.newast.NewToStringVisitor",
      "sqlancer.databend.DatabendToStringVisitor",
      "sqlancer.h2.H2ExpressionGenerator$H2UnaryPostfixOperator",
      "sqlancer.databend.ast.DatabendBinaryArithmeticOperation",
      "sqlancer.databend.ast.DatabendAggregateOperation",
      "sqlancer.databend.ast.DatabendLikeOperation",
      "sqlancer.h2.H2ExpressionGenerator$H2BinaryArithmeticOperator",
      "sqlancer.h2.H2ExpressionGenerator$H2UnaryPrefixOperator",
      "sqlancer.GlobalState",
      "sqlancer.SQLGlobalState",
      "sqlancer.databend.DatabendProvider$DatabendGlobalState",
      "sqlancer.common.query.Query",
      "sqlancer.common.query.SQLQueryAdapter",
      "sqlancer.common.query.ExpectedErrors",
      "sqlancer.IgnoreMeException",
      "sqlancer.h2.H2ExpressionGenerator$H2BinaryLogicalOperator",
      "sqlancer.materialize.MaterializeGlobalState"
    );
  }
}
