/**
 * Scaffolding file used to store all the setups needed to run 
 * tests automatically generated by EvoSuite
 * Mon Apr 14 08:50:07 GMT 2025
 */

package sqlancer.databend.test;

import org.evosuite.runtime.annotation.EvoSuiteClassExclude;
import org.junit.BeforeClass;
import org.junit.Before;
import org.junit.After;
import org.junit.AfterClass;
import org.evosuite.runtime.sandbox.Sandbox;
import org.evosuite.runtime.sandbox.Sandbox.SandboxMode;

import static org.evosuite.shaded.org.mockito.Mockito.*;
@EvoSuiteClassExclude
public class DatabendPivotedQuerySynthesisOracle_ESTest_scaffolding {

  @org.junit.Rule
  public org.evosuite.runtime.vnet.NonFunctionalRequirementRule nfr = new org.evosuite.runtime.vnet.NonFunctionalRequirementRule();

  private static final java.util.Properties defaultProperties = (java.util.Properties) java.lang.System.getProperties().clone(); 

  private org.evosuite.runtime.thread.ThreadStopper threadStopper =  new org.evosuite.runtime.thread.ThreadStopper (org.evosuite.runtime.thread.KillSwitchHandler.getInstance(), 3000);


  @BeforeClass
  public static void initEvoSuiteFramework() { 
    org.evosuite.runtime.RuntimeSettings.className = "sqlancer.databend.test.DatabendPivotedQuerySynthesisOracle"; 
    org.evosuite.runtime.GuiSupport.initialize(); 
    org.evosuite.runtime.RuntimeSettings.maxNumberOfThreads = 100; 
    org.evosuite.runtime.RuntimeSettings.maxNumberOfIterationsPerLoop = 10000; 
    org.evosuite.runtime.RuntimeSettings.mockSystemIn = true; 
    org.evosuite.runtime.RuntimeSettings.sandboxMode = org.evosuite.runtime.sandbox.Sandbox.SandboxMode.RECOMMENDED; 
    org.evosuite.runtime.sandbox.Sandbox.initializeSecurityManagerForSUT(); 
    org.evosuite.runtime.classhandling.JDKClassResetter.init();
    setSystemProperties();
    initializeClasses();
    org.evosuite.runtime.Runtime.getInstance().resetRuntime(); 
    try { initMocksToAvoidTimeoutsInTheTests(); } catch(ClassNotFoundException e) {} 
  } 

  @AfterClass
  public static void clearEvoSuiteFramework(){ 
    Sandbox.resetDefaultSecurityManager(); 
    java.lang.System.setProperties((java.util.Properties) defaultProperties.clone()); 
  } 

  @Before
  public void initTestCase(){ 
    threadStopper.storeCurrentThreads();
    threadStopper.startRecordingTime();
    org.evosuite.runtime.jvm.ShutdownHookHandler.getInstance().initHandler(); 
    org.evosuite.runtime.sandbox.Sandbox.goingToExecuteSUTCode(); 
    setSystemProperties(); 
    org.evosuite.runtime.GuiSupport.setHeadless(); 
    org.evosuite.runtime.Runtime.getInstance().resetRuntime(); 
    org.evosuite.runtime.agent.InstrumentingAgent.activate(); 
  } 

  @After
  public void doneWithTestCase(){ 
    threadStopper.killAndJoinClientThreads();
    org.evosuite.runtime.jvm.ShutdownHookHandler.getInstance().safeExecuteAddedHooks(); 
    org.evosuite.runtime.classhandling.JDKClassResetter.reset(); 
    resetClasses(); 
    org.evosuite.runtime.sandbox.Sandbox.doneWithExecutingSUTCode(); 
    org.evosuite.runtime.agent.InstrumentingAgent.deactivate(); 
    org.evosuite.runtime.GuiSupport.restoreHeadlessMode(); 
  } 

  public static void setSystemProperties() {
 
    java.lang.System.setProperties((java.util.Properties) defaultProperties.clone()); 
    java.lang.System.setProperty("user.dir", "E:\\Y2S2\\CS3213\\Sqlancer_original"); 
    java.lang.System.setProperty("java.io.tmpdir", "C:\\Users\\hp\\AppData\\Local\\Temp\\"); 
  }

  private static void initializeClasses() {
    org.evosuite.runtime.classhandling.ClassStateSupport.initializeClasses(DatabendPivotedQuerySynthesisOracle_ESTest_scaffolding.class.getClassLoader() ,
      "sqlancer.databend.DatabendSchema$DatabendTable",
      "sqlancer.AbstractAction",
      "sqlancer.common.ast.newast.NewOrderingTerm",
      "sqlancer.StatementExecutor",
      "sqlancer.databend.ast.DatabendUnaryPostfixOperation",
      "sqlancer.databend.DatabendExpectedValueVisitor",
      "sqlancer.common.ast.newast.NewPostfixTextNode",
      "sqlancer.databend.DatabendProvider$DatabendGlobalState",
      "sqlancer.SQLProviderAdapter",
      "sqlancer.databend.DatabendProvider",
      "sqlancer.databend.ast.DatabendConstant$DatabendFloatConstant",
      "sqlancer.common.ast.newast.NewFunctionNode",
      "sqlancer.databend.DatabendBugs",
      "sqlancer.common.ast.newast.NewCaseOperatorNode",
      "sqlancer.databend.DatabendErrors",
      "sqlancer.databend.DatabendSchema",
      "sqlancer.Main$StateLogger",
      "sqlancer.common.ast.newast.NewTernaryNode",
      "sqlancer.common.schema.AbstractTable",
      "sqlancer.common.query.ExpectedErrors",
      "sqlancer.databend.DatabendSchema$DatabendCompositeDataType",
      "sqlancer.GlobalState",
      "sqlancer.common.ast.newast.Select",
      "sqlancer.databend.ast.DatabendConstant$DatabendDateConstant",
      "sqlancer.databend.DatabendSchema$DatabendRowValue",
      "sqlancer.common.schema.AbstractSchema",
      "sqlancer.databend.ast.DatabendPostFixText",
      "sqlancer.databend.ast.DatabendConstant$DatabendStringConstant",
      "sqlancer.DatabaseProvider",
      "sqlancer.databend.ast.DatabendConstant$DatabendBooleanConstant",
      "sqlancer.common.schema.AbstractRelationalTable",
      "sqlancer.Main$QueryManager",
      "sqlancer.databend.ast.DatabendBinaryOperation",
      "sqlancer.databend.ast.DatabendSelect",
      "sqlancer.databend.test.DatabendPivotedQuerySynthesisOracle",
      "sqlancer.ProviderAdapter",
      "sqlancer.common.query.Query",
      "sqlancer.common.oracle.PivotedQuerySynthesisBase",
      "sqlancer.databend.ast.DatabendTableReference",
      "sqlancer.common.ast.newast.NewUnaryPostfixOperatorNode",
      "sqlancer.SQLancerDBConnection",
      "sqlancer.databend.ast.DatabendAlias",
      "sqlancer.MainOptions",
      "sqlancer.common.ast.newast.ColumnReferenceNode",
      "sqlancer.Randomly",
      "sqlancer.common.ast.BinaryNode",
      "sqlancer.common.ast.BinaryOperatorNode",
      "sqlancer.common.visitor.BinaryOperation",
      "sqlancer.databend.ast.DatabendOrderByTerm",
      "sqlancer.common.oracle.TestOracle",
      "sqlancer.common.ast.newast.NewToStringVisitor",
      "sqlancer.common.schema.AbstractTableColumn",
      "sqlancer.common.query.SQLancerResultSet",
      "sqlancer.databend.ast.DatabendConstant",
      "sqlancer.common.ast.newast.NewAliasNode",
      "sqlancer.databend.ast.DatabendColumnValue",
      "sqlancer.common.query.SQLQueryAdapter",
      "sqlancer.databend.ast.DatabendConstant$DatabendIntConstant",
      "sqlancer.common.query.SQLQueryResultCheckAdapter",
      "sqlancer.common.ast.newast.Expression",
      "sqlancer.databend.DatabendProvider$Action",
      "sqlancer.SQLGlobalState",
      "sqlancer.common.ast.BinaryOperatorNode$Operator",
      "sqlancer.StateToReproduce",
      "sqlancer.databend.ast.DatabendInOperation",
      "sqlancer.common.ast.newast.NewBinaryOperatorNode",
      "sqlancer.databend.ast.DatabendUnaryPostfixOperation$DatabendUnaryPostfixOperator$1",
      "sqlancer.databend.ast.DatabendUnaryPostfixOperation$DatabendUnaryPostfixOperator$2",
      "sqlancer.SQLConnection",
      "sqlancer.databend.DatabendSchema$DatabendColumn",
      "sqlancer.databend.ast.DatabendBetweenOperation",
      "sqlancer.databend.DatabendSchema$DatabendDataType",
      "sqlancer.databend.ast.DatabendFunctionOperation",
      "sqlancer.DBMSSpecificOptions",
      "sqlancer.common.ast.newast.NewBetweenOperatorNode",
      "sqlancer.common.ast.newast.NewInOperatorNode",
      "sqlancer.IgnoreMeException",
      "sqlancer.common.log.Loggable",
      "sqlancer.databend.ast.DatabendConstant$DatabendNullConstant",
      "sqlancer.databend.ast.DatabendColumnReference",
      "sqlancer.common.ast.newast.NewUnaryPrefixOperatorNode",
      "sqlancer.common.ast.SelectBase",
      "sqlancer.databend.ast.DatabendConstant$DatabendTimestampConstant",
      "sqlancer.common.schema.AbstractRowValue",
      "sqlancer.databend.ast.DatabendExpression",
      "sqlancer.databend.DatabendToStringVisitor",
      "sqlancer.databend.ast.DatabendUnaryPostfixOperation$DatabendUnaryPostfixOperator",
      "sqlancer.databend.ast.DatabendUnaryPrefixOperation",
      "sqlancer.Reproducer",
      "sqlancer.common.ast.newast.TableReferenceNode"
    );
  } 
  private static void initMocksToAvoidTimeoutsInTheTests() throws ClassNotFoundException { 
    mock(Class.forName("java.util.function.Consumer", false, DatabendPivotedQuerySynthesisOracle_ESTest_scaffolding.class.getClassLoader()));
  }

  private static void resetClasses() {
    org.evosuite.runtime.classhandling.ClassResetter.getInstance().setClassLoader(DatabendPivotedQuerySynthesisOracle_ESTest_scaffolding.class.getClassLoader()); 

    org.evosuite.runtime.classhandling.ClassStateSupport.resetClasses(
      "sqlancer.common.oracle.PivotedQuerySynthesisBase",
      "sqlancer.databend.test.DatabendPivotedQuerySynthesisOracle",
      "sqlancer.databend.DatabendBugs",
      "sqlancer.Randomly$StringGenerationStrategy$4",
      "sqlancer.Randomly$StringGenerationStrategy",
      "sqlancer.Randomly",
      "sqlancer.databend.DatabendSchema$DatabendDataType",
      "sqlancer.databend.ast.DatabendUnaryPostfixOperation$DatabendUnaryPostfixOperator",
      "sqlancer.databend.ast.DatabendUnaryPrefixOperation$DatabendUnaryPrefixOperator",
      "sqlancer.GlobalState",
      "sqlancer.SQLGlobalState",
      "sqlancer.databend.DatabendProvider$DatabendGlobalState",
      "sqlancer.common.query.ExpectedErrors",
      "sqlancer.databend.DatabendErrors",
      "sqlancer.common.schema.AbstractSchema",
      "sqlancer.databend.DatabendSchema",
      "sqlancer.common.gen.TypedExpressionGenerator",
      "sqlancer.databend.gen.DatabendNewExpressionGenerator",
      "sqlancer.common.query.ExpectedErrors$ExpectedErrorsBuilder",
      "sqlancer.common.query.Query",
      "sqlancer.common.query.SQLQueryAdapter",
      "sqlancer.databend.ast.DatabendConstant",
      "sqlancer.databend.ast.DatabendConstant$DatabendTimestampConstant",
      "sqlancer.databend.DatabendExpectedValueVisitor",
      "sqlancer.common.query.SQLQueryResultCheckAdapter",
      "sqlancer.databend.ast.DatabendConstant$DatabendNullConstant",
      "sqlancer.databend.ast.DatabendConstant$DatabendIntConstant",
      "sqlancer.databend.ast.DatabendConstant$DatabendDateConstant",
      "sqlancer.databend.ast.DatabendConstant$DatabendFloatConstant",
      "sqlancer.databend.ast.DatabendConstant$DatabendBooleanConstant",
      "sqlancer.datafusion.DataFusionProvider$DataFusionGlobalState",
      "sqlancer.datafusion.DataFusionUtil$DataFusionInstanceID",
      "sqlancer.datafusion.DataFusionUtil$DataFusionLogger",
      "sqlancer.databend.DatabendSchema$DatabendCompositeDataType",
      "sqlancer.common.schema.AbstractTableColumn",
      "sqlancer.databend.DatabendSchema$DatabendColumn",
      "sqlancer.common.ast.newast.ColumnReferenceNode",
      "sqlancer.databend.ast.DatabendColumnValue",
      "sqlancer.materialize.MaterializeGlobalState",
      "sqlancer.databend.ast.DatabendConstant$DatabendStringConstant",
      "sqlancer.common.ast.newast.NewToStringVisitor",
      "sqlancer.databend.DatabendToStringVisitor",
      "sqlancer.common.ast.newast.NewBinaryOperatorNode",
      "sqlancer.databend.ast.DatabendBinaryComparisonOperation",
      "sqlancer.common.ast.newast.NewOrderingTerm",
      "sqlancer.databend.ast.DatabendOrderByTerm",
      "sqlancer.common.ast.newast.NewUnaryPostfixOperatorNode",
      "sqlancer.databend.ast.DatabendCastOperation",
      "sqlancer.databend.ast.DatabendCastOperation$1",
      "sqlancer.clickhouse.ClickHouseProvider$ClickHouseGlobalState",
      "sqlancer.common.ast.newast.NewBetweenOperatorNode",
      "sqlancer.databend.ast.DatabendBetweenOperation",
      "sqlancer.databend.ast.DatabendBinaryLogicalOperation",
      "sqlancer.postgres.PostgresGlobalState",
      "sqlancer.citus.CitusGlobalState",
      "sqlancer.common.schema.AbstractTable",
      "sqlancer.common.schema.AbstractRelationalTable",
      "sqlancer.databend.DatabendSchema$DatabendTable",
      "sqlancer.common.ast.newast.TableReferenceNode",
      "sqlancer.databend.ast.DatabendTableReference",
      "sqlancer.databend.ast.DatabendJoin",
      "sqlancer.databend.ast.DatabendUnaryPostfixOperation",
      "sqlancer.databend.ast.DatabendLikeOperation",
      "sqlancer.databend.ast.DatabendBinaryArithmeticOperation",
      "sqlancer.common.ast.newast.NewUnaryPrefixOperatorNode",
      "sqlancer.databend.ast.DatabendUnaryPrefixOperation",
      "sqlancer.databend.ast.DatabendColumnReference",
      "sqlancer.common.ast.SelectBase",
      "sqlancer.databend.ast.DatabendSelect",
      "sqlancer.common.ast.newast.NewPostfixTextNode",
      "sqlancer.databend.ast.DatabendPostFixText",
      "sqlancer.h2.H2ExpressionGenerator$H2BinaryArithmeticOperator",
      "sqlancer.common.ast.newast.NewAliasNode",
      "sqlancer.databend.ast.DatabendAlias",
      "sqlancer.common.ast.newast.NewInOperatorNode",
      "sqlancer.databend.ast.DatabendInOperation",
      "sqlancer.h2.H2ExpressionGenerator$H2UnaryPostfixOperator",
      "sqlancer.databend.ast.DatabendBinaryOperation",
      "sqlancer.common.ast.newast.NewFunctionNode",
      "sqlancer.databend.ast.DatabendFunctionOperation",
      "sqlancer.databend.ast.DatabendAggregateOperation",
      "sqlancer.IgnoreMeException",
      "sqlancer.h2.H2ExpressionGenerator$H2UnaryPrefixOperator"
    );
  }
}
