/**
 * Scaffolding file used to store all the setups needed to run 
 * tests automatically generated by EvoSuite
 * Thu Apr 10 15:12:22 GMT 2025
 */

package sqlancer.cnosdb;

import org.evosuite.runtime.annotation.EvoSuiteClassExclude;
import org.junit.BeforeClass;
import org.junit.Before;
import org.junit.After;
import org.junit.AfterClass;
import org.evosuite.runtime.sandbox.Sandbox;
import org.evosuite.runtime.sandbox.Sandbox.SandboxMode;

@EvoSuiteClassExclude
public class CnosDBToStringVisitor_ESTest_scaffolding {

  @org.junit.Rule
  public org.evosuite.runtime.vnet.NonFunctionalRequirementRule nfr = new org.evosuite.runtime.vnet.NonFunctionalRequirementRule();

  private static final java.util.Properties defaultProperties = (java.util.Properties) java.lang.System.getProperties().clone(); 

  private org.evosuite.runtime.thread.ThreadStopper threadStopper =  new org.evosuite.runtime.thread.ThreadStopper (org.evosuite.runtime.thread.KillSwitchHandler.getInstance(), 3000);


  @BeforeClass
  public static void initEvoSuiteFramework() { 
    org.evosuite.runtime.RuntimeSettings.className = "sqlancer.cnosdb.CnosDBToStringVisitor"; 
    org.evosuite.runtime.GuiSupport.initialize(); 
    org.evosuite.runtime.RuntimeSettings.maxNumberOfThreads = 100; 
    org.evosuite.runtime.RuntimeSettings.maxNumberOfIterationsPerLoop = 10000; 
    org.evosuite.runtime.RuntimeSettings.mockSystemIn = true; 
    org.evosuite.runtime.RuntimeSettings.sandboxMode = org.evosuite.runtime.sandbox.Sandbox.SandboxMode.RECOMMENDED; 
    org.evosuite.runtime.sandbox.Sandbox.initializeSecurityManagerForSUT(); 
    org.evosuite.runtime.classhandling.JDKClassResetter.init();
    setSystemProperties();
    initializeClasses();
    org.evosuite.runtime.Runtime.getInstance().resetRuntime(); 
  } 

  @AfterClass
  public static void clearEvoSuiteFramework(){ 
    Sandbox.resetDefaultSecurityManager(); 
    java.lang.System.setProperties((java.util.Properties) defaultProperties.clone()); 
  } 

  @Before
  public void initTestCase(){ 
    threadStopper.storeCurrentThreads();
    threadStopper.startRecordingTime();
    org.evosuite.runtime.jvm.ShutdownHookHandler.getInstance().initHandler(); 
    org.evosuite.runtime.sandbox.Sandbox.goingToExecuteSUTCode(); 
    setSystemProperties(); 
    org.evosuite.runtime.GuiSupport.setHeadless(); 
    org.evosuite.runtime.Runtime.getInstance().resetRuntime(); 
    org.evosuite.runtime.agent.InstrumentingAgent.activate(); 
  } 

  @After
  public void doneWithTestCase(){ 
    threadStopper.killAndJoinClientThreads();
    org.evosuite.runtime.jvm.ShutdownHookHandler.getInstance().safeExecuteAddedHooks(); 
    org.evosuite.runtime.classhandling.JDKClassResetter.reset(); 
    resetClasses(); 
    org.evosuite.runtime.sandbox.Sandbox.doneWithExecutingSUTCode(); 
    org.evosuite.runtime.agent.InstrumentingAgent.deactivate(); 
    org.evosuite.runtime.GuiSupport.restoreHeadlessMode(); 
  } 

  public static void setSystemProperties() {
 
    java.lang.System.setProperties((java.util.Properties) defaultProperties.clone()); 
    java.lang.System.setProperty("user.dir", "E:\\Y2S2\\CS3213\\Sqlancer_original"); 
    java.lang.System.setProperty("java.io.tmpdir", "C:\\Users\\hp\\AppData\\Local\\Temp\\"); 
  }

  private static void initializeClasses() {
    org.evosuite.runtime.classhandling.ClassStateSupport.initializeClasses(CnosDBToStringVisitor_ESTest_scaffolding.class.getClassLoader() ,
      "sqlancer.cnosdb.ast.CnosDBPrefixOperation",
      "sqlancer.Randomly$StringGenerationStrategy",
      "sqlancer.cnosdb.ast.CnosDBPostfixOperation$PostfixOperator",
      "sqlancer.common.ast.FunctionNode",
      "sqlancer.common.visitor.ToStringVisitor",
      "sqlancer.cnosdb.ast.CnosDBCastOperation",
      "sqlancer.cnosdb.ast.CnosDBAggregate$CnosDBAggregateFunction",
      "sqlancer.common.visitor.NodeVisitor",
      "sqlancer.common.query.Query",
      "sqlancer.cnosdb.CnosDBSchema$CnosDBDataType",
      "sqlancer.cnosdb.ast.CnosDBColumnValue",
      "sqlancer.SQLancerDBConnection",
      "sqlancer.cnosdb.ast.CnosDBPostfixOperation$PostfixOperator$1",
      "sqlancer.MainOptions",
      "sqlancer.cnosdb.ast.CnosDBPostfixOperation$PostfixOperator$3",
      "sqlancer.cnosdb.ast.CnosDBConstant$StringConstant",
      "sqlancer.cnosdb.ast.CnosDBPostfixOperation$PostfixOperator$2",
      "sqlancer.cnosdb.ast.CnosDBAggregate$CnosDBAggregateFunction$6",
      "sqlancer.cnosdb.ast.CnosDBAggregate$CnosDBAggregateFunction$7",
      "sqlancer.cnosdb.ast.CnosDBAggregate$CnosDBAggregateFunction$4",
      "sqlancer.cnosdb.ast.CnosDBAggregate$CnosDBAggregateFunction$5",
      "sqlancer.common.ast.BinaryOperatorNode",
      "sqlancer.cnosdb.ast.CnosDBAggregate$CnosDBAggregateFunction$2",
      "sqlancer.cnosdb.ast.CnosDBPostfixOperation$PostfixOperator$5",
      "sqlancer.cnosdb.ast.CnosDBAggregate$CnosDBAggregateFunction$3",
      "sqlancer.cnosdb.ast.CnosDBPostfixOperation$PostfixOperator$4",
      "sqlancer.cnosdb.ast.CnosDBAggregate$CnosDBAggregateFunction$1",
      "sqlancer.cnosdb.ast.CnosDBPostfixOperation$PostfixOperator$6",
      "sqlancer.cnosdb.ast.CnosDBConstant$TimeStampConstant",
      "sqlancer.cnosdb.ast.CnosDBFunction",
      "sqlancer.cnosdb.ast.CnosDBPrefixOperation$PrefixOperator$2",
      "sqlancer.cnosdb.ast.CnosDBPrefixOperation$PrefixOperator$3",
      "sqlancer.common.schema.AbstractTableColumn",
      "sqlancer.cnosdb.ast.CnosDBConstant$DoubleConstant",
      "sqlancer.cnosdb.CnosDBSchema$CnosDBTable",
      "sqlancer.cnosdb.ast.CnosDBPrefixOperation$PrefixOperator$1",
      "sqlancer.cnosdb.CnosDBVisitor",
      "sqlancer.common.ast.BinaryOperatorNode$Operator",
      "sqlancer.cnosdb.ast.CnosDBOrderByTerm",
      "sqlancer.cnosdb.ast.CnosDBPostfixText",
      "sqlancer.cnosdb.ast.CnosDBPostfixOperation",
      "sqlancer.DBMSSpecificOptions",
      "sqlancer.cnosdb.ast.CnosDBLikeOperation",
      "sqlancer.cnosdb.ast.CnosDBInOperation",
      "sqlancer.common.schema.TableIndex",
      "sqlancer.cnosdb.CnosDBSchema$CnosDBFieldColumn",
      "sqlancer.cnosdb.ast.CnosDBBinaryComparisonOperation$CnosDBBinaryComparisonOperator",
      "sqlancer.cnosdb.CnosDBSchema$CnosDBRowValue",
      "sqlancer.cnosdb.ast.CnosDBSelect$SelectType",
      "sqlancer.common.gen.ExpressionGenerator",
      "sqlancer.cnosdb.ast.CnosDBBetweenOperation",
      "sqlancer.cnosdb.ast.CnosDBJoin",
      "sqlancer.cnosdb.ast.CnosDBSimilarTo",
      "sqlancer.Main$StateLogger",
      "sqlancer.cnosdb.CnosDBSchema$CnosDBColumn",
      "sqlancer.cnosdb.ast.CnosDBAlias",
      "sqlancer.common.visitor.UnaryOperation",
      "sqlancer.common.schema.AbstractTable",
      "sqlancer.GlobalState",
      "sqlancer.cnosdb.ast.CnosDBSelect",
      "sqlancer.cnosdb.ast.CnosDBPrefixOperation$PrefixOperator",
      "sqlancer.common.schema.AbstractSchema",
      "sqlancer.cnosdb.ast.CnosDBAggregate",
      "sqlancer.cnosdb.ast.CnosDBBinaryComparisonOperation",
      "sqlancer.cnosdb.ast.CnosDBConstant$BooleanConstant",
      "sqlancer.cnosdb.ast.CnosDBBinaryLogicalOperation",
      "sqlancer.cnosdb.ast.CnosDBOrderByTerm$CnosDBOrder",
      "sqlancer.Main$QueryManager",
      "sqlancer.cnosdb.CnosDBGlobalState",
      "sqlancer.cnosdb.ast.CnosDBConstant$CnosDBNullConstant",
      "sqlancer.cnosdb.ast.CnosDBConstant$IntConstant",
      "sqlancer.cnosdb.ast.CnosDBSelect$CnosDBFromTable",
      "sqlancer.Randomly",
      "sqlancer.cnosdb.ast.CnosDBConstant",
      "sqlancer.cnosdb.gen.CnosDBExpressionGenerator",
      "sqlancer.cnosdb.ast.CnosDBExpression",
      "sqlancer.cnosdb.ast.CnosDBSelect$CnosDBSubquery",
      "sqlancer.common.ast.BinaryNode",
      "sqlancer.common.visitor.BinaryOperation",
      "sqlancer.common.query.SQLancerResultSet",
      "sqlancer.cnosdb.ast.CnosDBJoin$CnosDBJoinType",
      "sqlancer.cnosdb.CnosDBSchema",
      "sqlancer.Randomly$StringGenerationStrategy$4",
      "sqlancer.StateToReproduce",
      "sqlancer.Randomly$StringGenerationStrategy$3",
      "sqlancer.Randomly$StringGenerationStrategy$2",
      "sqlancer.Randomly$StringGenerationStrategy$1",
      "sqlancer.cnosdb.ast.CnosDBFunctionWithUnknownResult",
      "sqlancer.cnosdb.CnosDBToStringVisitor",
      "sqlancer.cnosdb.CnosDBCompoundDataType",
      "sqlancer.cnosdb.ast.CnosDBBinaryComparisonOperation$CnosDBBinaryComparisonOperator$1",
      "sqlancer.cnosdb.ast.CnosDBBinaryComparisonOperation$CnosDBBinaryComparisonOperator$2",
      "sqlancer.cnosdb.ast.CnosDBBinaryComparisonOperation$CnosDBBinaryComparisonOperator$3",
      "sqlancer.cnosdb.ast.CnosDBBinaryComparisonOperation$CnosDBBinaryComparisonOperator$4",
      "sqlancer.cnosdb.ast.CnosDBBinaryComparisonOperation$CnosDBBinaryComparisonOperator$5",
      "sqlancer.cnosdb.ast.CnosDBBinaryComparisonOperation$CnosDBBinaryComparisonOperator$6",
      "sqlancer.cnosdb.ast.CnosDBBinaryComparisonOperation$CnosDBBinaryComparisonOperator$7",
      "sqlancer.cnosdb.ast.CnosDBBinaryComparisonOperation$CnosDBBinaryComparisonOperator$8",
      "sqlancer.cnosdb.ast.CnosDBBinaryLogicalOperation$BinaryLogicalOperator",
      "sqlancer.common.visitor.UnaryOperation$OperatorKind",
      "sqlancer.IgnoreMeException",
      "sqlancer.common.log.Loggable",
      "sqlancer.common.ast.SelectBase",
      "sqlancer.common.schema.AbstractRowValue"
    );
  } 

  private static void resetClasses() {
    org.evosuite.runtime.classhandling.ClassResetter.getInstance().setClassLoader(CnosDBToStringVisitor_ESTest_scaffolding.class.getClassLoader()); 

    org.evosuite.runtime.classhandling.ClassStateSupport.resetClasses(
      "sqlancer.common.visitor.NodeVisitor",
      "sqlancer.common.visitor.ToStringVisitor",
      "sqlancer.cnosdb.CnosDBToStringVisitor",
      "sqlancer.cnosdb.ast.CnosDBSelect$SelectType",
      "sqlancer.Randomly$StringGenerationStrategy$4",
      "sqlancer.Randomly$StringGenerationStrategy",
      "sqlancer.Randomly",
      "sqlancer.cnosdb.ast.CnosDBJoin$CnosDBJoinType",
      "sqlancer.cnosdb.CnosDBSchema$CnosDBDataType",
      "sqlancer.GlobalState",
      "sqlancer.cnosdb.CnosDBGlobalState",
      "sqlancer.cnosdb.gen.CnosDBExpressionGenerator",
      "sqlancer.common.ast.SelectBase",
      "sqlancer.cnosdb.ast.CnosDBSelect",
      "sqlancer.cnosdb.ast.CnosDBConstant",
      "sqlancer.cnosdb.ast.CnosDBConstant$DoubleConstant",
      "sqlancer.common.schema.AbstractTableColumn",
      "sqlancer.cnosdb.CnosDBSchema$CnosDBColumn",
      "sqlancer.cnosdb.ast.CnosDBColumnValue",
      "sqlancer.cnosdb.ast.CnosDBBetweenOperation",
      "sqlancer.cnosdb.ast.CnosDBConstant$BooleanConstant",
      "sqlancer.cnosdb.ast.CnosDBOrderByTerm",
      "sqlancer.cnosdb.ast.CnosDBSelect$CnosDBSubquery",
      "sqlancer.cnosdb.ast.CnosDBConstant$StringConstant",
      "sqlancer.cnosdb.ast.CnosDBConstant$IntConstant",
      "sqlancer.cnosdb.ast.CnosDBPrefixOperation",
      "sqlancer.common.ast.BinaryNode",
      "sqlancer.cnosdb.ast.CnosDBConcatOperation",
      "sqlancer.cnosdb.ast.CnosDBSimilarTo",
      "sqlancer.cnosdb.ast.CnosDBInOperation",
      "sqlancer.cnosdb.ast.CnosDBPostfixOperation",
      "sqlancer.common.ast.FunctionNode",
      "sqlancer.cnosdb.ast.CnosDBAggregate",
      "sqlancer.common.ast.BinaryOperatorNode",
      "sqlancer.cnosdb.ast.CnosDBBinaryLogicalOperation",
      "sqlancer.cnosdb.ast.CnosDBConstant$CnosDBNullConstant",
      "sqlancer.cnosdb.ast.CnosDBLikeOperation",
      "sqlancer.cnosdb.ast.CnosDBBinaryComparisonOperation",
      "sqlancer.cnosdb.ast.CnosDBAlias",
      "sqlancer.cnosdb.ast.CnosDBConstant$TimeStampConstant",
      "sqlancer.cnosdb.CnosDBCompoundDataType",
      "sqlancer.cnosdb.ast.CnosDBCastOperation",
      "sqlancer.cnosdb.ast.CnosDBPostfixText",
      "sqlancer.common.schema.AbstractTable",
      "sqlancer.cnosdb.CnosDBSchema$CnosDBTable",
      "sqlancer.cnosdb.ast.CnosDBFunction",
      "sqlancer.cnosdb.ast.CnosDBSelect$CnosDBFromTable",
      "sqlancer.common.visitor.UnaryOperation$OperatorKind",
      "sqlancer.cnosdb.ast.CnosDBJoin",
      "sqlancer.cnosdb.ast.CnosDBBinaryArithmeticOperation",
      "sqlancer.common.schema.AbstractRelationalTable",
      "sqlancer.cnosdb.CnosDBSchema$CnosDBTimeColumn",
      "sqlancer.common.query.Query",
      "sqlancer.tidb.TiDBSchema$TiDBCompositeDataType",
      "sqlancer.tidb.TiDBSchema$TiDBColumn",
      "sqlancer.tidb.TiDBSchema$TiDBTable",
      "sqlancer.oceanbase.OceanBaseSchema$OceanBaseColumn"
    );
  }
}
