/*
 * This file was automatically generated by EvoSuite
 * Mon Apr 14 05:47:36 GMT 2025
 */

package sqlancer.cockroachdb.ast;

import org.junit.Test;
import static org.junit.Assert.*;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;
import sqlancer.cockroachdb.ast.CockroachDBCollate;
import sqlancer.cockroachdb.ast.CockroachDBConstant;
import sqlancer.cockroachdb.ast.CockroachDBExpression;
import sqlancer.cockroachdb.ast.CockroachDBSelect;
import sqlancer.common.visitor.UnaryOperation;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true) 
public class CockroachDBCollate_ESTest extends CockroachDBCollate_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      CockroachDBConstant.CockroachDBBitConstant cockroachDBConstant_CockroachDBBitConstant0 = new CockroachDBConstant.CockroachDBBitConstant("5p>kxd^ezT");
      CockroachDBCollate cockroachDBCollate0 = new CockroachDBCollate(cockroachDBConstant_CockroachDBBitConstant0, "sqlancer.doris.DorisProvider");
      String string0 = cockroachDBCollate0.getCollate();
      assertEquals("sqlancer.doris.DorisProvider", string0);
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      CockroachDBConstant.CockroachDBIntConstant cockroachDBConstant_CockroachDBIntConstant0 = new CockroachDBConstant.CockroachDBIntConstant((-488L));
      CockroachDBCollate cockroachDBCollate0 = new CockroachDBCollate(cockroachDBConstant_CockroachDBIntConstant0, "");
      String string0 = cockroachDBCollate0.getCollate();
      assertEquals("", string0);
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      CockroachDBExpression cockroachDBExpression0 = CockroachDBConstant.createTimeConstant(0L);
      CockroachDBCollate cockroachDBCollate0 = new CockroachDBCollate(cockroachDBExpression0, (String) null);
      String string0 = cockroachDBCollate0.getCollate();
      assertNull(string0);
  }

  @Test(timeout = 4000)
  public void test3()  throws Throwable  {
      CockroachDBExpression cockroachDBExpression0 = CockroachDBConstant.createTimeConstant(0L);
      CockroachDBCollate cockroachDBCollate0 = new CockroachDBCollate(cockroachDBExpression0, (String) null);
      String string0 = cockroachDBCollate0.getOperatorRepresentation();
      assertEquals("COLLATE null", string0);
  }

  @Test(timeout = 4000)
  public void test4()  throws Throwable  {
      CockroachDBSelect cockroachDBSelect0 = new CockroachDBSelect();
      CockroachDBCollate cockroachDBCollate0 = new CockroachDBCollate(cockroachDBSelect0, "NmDp-TE{|%^Fv");
      UnaryOperation.OperatorKind unaryOperation_OperatorKind0 = cockroachDBCollate0.getOperatorKind();
      assertEquals(UnaryOperation.OperatorKind.POSTFIX, unaryOperation_OperatorKind0);
  }
}
