/*
 * This file was automatically generated by EvoSuite
 * Mon Apr 14 05:16:50 GMT 2025
 */

package sqlancer.cockroachdb.ast;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import java.util.List;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;
import sqlancer.cockroachdb.ast.CockroachDBConstant;
import sqlancer.cockroachdb.ast.CockroachDBExpression;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true) 
public class CockroachDBConstant_ESTest extends CockroachDBConstant_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test00()  throws Throwable  {
      CockroachDBExpression cockroachDBExpression0 = CockroachDBConstant.createIntervalConstant(2259L, 0L, 2259L, 0L, 0L, 2086L);
      assertNotNull(cockroachDBExpression0);
  }

  @Test(timeout = 4000)
  public void test01()  throws Throwable  {
      CockroachDBConstant.CockroachDBBitConstant cockroachDBConstant_CockroachDBBitConstant0 = (CockroachDBConstant.CockroachDBBitConstant)CockroachDBConstant.createBitConstantWithSize((-147));
      assertEquals("", cockroachDBConstant_CockroachDBBitConstant0.getValue());
  }

  @Test(timeout = 4000)
  public void test02()  throws Throwable  {
      CockroachDBExpression cockroachDBExpression0 = CockroachDBConstant.createIntervalConstant(1461L, (-353L), (-353L), 9223372036854775807L, 772L, 0L);
      assertNotNull(cockroachDBExpression0);
  }

  @Test(timeout = 4000)
  public void test03()  throws Throwable  {
      CockroachDBConstant.CockroachDBIntConstant cockroachDBConstant_CockroachDBIntConstant0 = CockroachDBConstant.createIntConstant(0L);
      assertEquals(0L, cockroachDBConstant_CockroachDBIntConstant0.getValue());
  }

  @Test(timeout = 4000)
  public void test04()  throws Throwable  {
      CockroachDBConstant.CockroachDBIntConstant cockroachDBConstant_CockroachDBIntConstant0 = CockroachDBConstant.createIntConstant((-1096L));
      assertEquals((-1096L), cockroachDBConstant_CockroachDBIntConstant0.getValue());
  }

  @Test(timeout = 4000)
  public void test05()  throws Throwable  {
      CockroachDBConstant.CockroachDBDoubleConstant cockroachDBConstant_CockroachDBDoubleConstant0 = CockroachDBConstant.createFloatConstant(0.0);
      assertEquals(0.0, cockroachDBConstant_CockroachDBDoubleConstant0.getValue(), 0.01);
  }

  @Test(timeout = 4000)
  public void test06()  throws Throwable  {
      // Undeclared exception!
      CockroachDBConstant.createBitConstantWithSize(2575053);
  }

  @Test(timeout = 4000)
  public void test07()  throws Throwable  {
      CockroachDBConstant.CockroachDBNullConstant cockroachDBConstant_CockroachDBNullConstant0 = new CockroachDBConstant.CockroachDBNullConstant();
      assertEquals("NULL", cockroachDBConstant_CockroachDBNullConstant0.toString());
  }

  @Test(timeout = 4000)
  public void test08()  throws Throwable  {
      CockroachDBConstant.CockroachDBTimeRelatedConstant cockroachDBConstant_CockroachDBTimeRelatedConstant0 = new CockroachDBConstant.CockroachDBTimeRelatedConstant("Kk<", 1570L, "");
  }

  @Test(timeout = 4000)
  public void test09()  throws Throwable  {
      CockroachDBConstant.CockroachDBBitConstant cockroachDBConstant_CockroachDBBitConstant0 = new CockroachDBConstant.CockroachDBBitConstant((-755L));
      assertEquals("1111111111111111111111111111111111111111111111111111110100001101", cockroachDBConstant_CockroachDBBitConstant0.getValue());
  }

  @Test(timeout = 4000)
  public void test10()  throws Throwable  {
      CockroachDBConstant.CockroachDBNullConstant cockroachDBConstant_CockroachDBNullConstant0 = CockroachDBConstant.createNullConstant();
      List<CockroachDBExpression> list0 = List.of((CockroachDBExpression) cockroachDBConstant_CockroachDBNullConstant0, (CockroachDBExpression) cockroachDBConstant_CockroachDBNullConstant0, (CockroachDBExpression) cockroachDBConstant_CockroachDBNullConstant0);
      CockroachDBConstant.CockroachDBArrayConstant cockroachDBConstant_CockroachDBArrayConstant0 = new CockroachDBConstant.CockroachDBArrayConstant(list0);
      String string0 = cockroachDBConstant_CockroachDBArrayConstant0.toString();
      assertNotNull(string0);
  }

  @Test(timeout = 4000)
  public void test11()  throws Throwable  {
      CockroachDBConstant.CockroachDBDoubleConstant cockroachDBConstant_CockroachDBDoubleConstant0 = CockroachDBConstant.createFloatConstant(Double.NEGATIVE_INFINITY);
      String string0 = cockroachDBConstant_CockroachDBDoubleConstant0.toString();
      assertEquals("FLOAT '-Inf'", string0);
  }

  @Test(timeout = 4000)
  public void test12()  throws Throwable  {
      CockroachDBConstant.CockroachDBDoubleConstant cockroachDBConstant_CockroachDBDoubleConstant0 = CockroachDBConstant.createFloatConstant(Double.POSITIVE_INFINITY);
      String string0 = cockroachDBConstant_CockroachDBDoubleConstant0.toString();
      assertEquals("FLOAT '+Inf'", string0);
  }

  @Test(timeout = 4000)
  public void test13()  throws Throwable  {
      CockroachDBConstant.CockroachDBBooleanConstant cockroachDBConstant_CockroachDBBooleanConstant0 = new CockroachDBConstant.CockroachDBBooleanConstant(false);
      boolean boolean0 = cockroachDBConstant_CockroachDBBooleanConstant0.getValue();
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test14()  throws Throwable  {
      CockroachDBConstant.CockroachDBIntConstant cockroachDBConstant_CockroachDBIntConstant0 = new CockroachDBConstant.CockroachDBIntConstant((-1636L));
      long long0 = cockroachDBConstant_CockroachDBIntConstant0.getValue();
      assertEquals((-1636L), long0);
  }

  @Test(timeout = 4000)
  public void test15()  throws Throwable  {
      CockroachDBConstant.CockroachDBIntConstant cockroachDBConstant_CockroachDBIntConstant0 = new CockroachDBConstant.CockroachDBIntConstant(226);
      String string0 = cockroachDBConstant_CockroachDBIntConstant0.toString();
      assertEquals("226", string0);
  }

  @Test(timeout = 4000)
  public void test16()  throws Throwable  {
      CockroachDBConstant.CockroachDBTimeRelatedConstant cockroachDBConstant_CockroachDBTimeRelatedConstant0 = (CockroachDBConstant.CockroachDBTimeRelatedConstant)CockroachDBConstant.createTimestamptzConstant((-755L));
      String string0 = cockroachDBConstant_CockroachDBTimeRelatedConstant0.toString();
      assertEquals("TIMESTAMPTZ '1969-12-31T23:59:59'", string0);
  }

  @Test(timeout = 4000)
  public void test17()  throws Throwable  {
      CockroachDBConstant.CockroachDBBitConstant cockroachDBConstant_CockroachDBBitConstant0 = new CockroachDBConstant.CockroachDBBitConstant("s\"d`^TmTSR;VpV");
      String string0 = cockroachDBConstant_CockroachDBBitConstant0.getValue();
      assertEquals("s\"d`^TmTSR;VpV", string0);
  }

  @Test(timeout = 4000)
  public void test18()  throws Throwable  {
      CockroachDBConstant.CockroachDBBitConstant cockroachDBConstant_CockroachDBBitConstant0 = (CockroachDBConstant.CockroachDBBitConstant)CockroachDBConstant.createBitConstantWithSize(205);
      String string0 = cockroachDBConstant_CockroachDBBitConstant0.toString();
      assertEquals("B'1111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111'", string0);
  }

  @Test(timeout = 4000)
  public void test19()  throws Throwable  {
      CockroachDBConstant.CockroachDBIntervalConstant cockroachDBConstant_CockroachDBIntervalConstant0 = new CockroachDBConstant.CockroachDBIntervalConstant(0L, 0L, (-387L), 0L, 0L, 234L);
      String string0 = cockroachDBConstant_CockroachDBIntervalConstant0.toString();
      assertEquals("(INTERVAL '0 year 0 months -387 days 0 hours 0 minutes 234 seconds')", string0);
  }

  @Test(timeout = 4000)
  public void test20()  throws Throwable  {
      CockroachDBConstant.CockroachDBTextConstant cockroachDBConstant_CockroachDBTextConstant0 = new CockroachDBConstant.CockroachDBTextConstant("`]uT///");
      String string0 = cockroachDBConstant_CockroachDBTextConstant0.toString();
      assertEquals("'`]uT///'", string0);
  }

  @Test(timeout = 4000)
  public void test21()  throws Throwable  {
      CockroachDBConstant.CockroachDBTextConstant cockroachDBConstant_CockroachDBTextConstant0 = new CockroachDBConstant.CockroachDBTextConstant("`]uT///");
      String string0 = cockroachDBConstant_CockroachDBTextConstant0.getValue();
      assertEquals("`]uT///", string0);
  }

  @Test(timeout = 4000)
  public void test22()  throws Throwable  {
      CockroachDBConstant.CockroachDBArrayConstant cockroachDBConstant_CockroachDBArrayConstant0 = new CockroachDBConstant.CockroachDBArrayConstant((List<CockroachDBExpression>) null);
      List<CockroachDBExpression> list0 = cockroachDBConstant_CockroachDBArrayConstant0.getElements();
      assertNull(list0);
  }

  @Test(timeout = 4000)
  public void test23()  throws Throwable  {
      CockroachDBExpression cockroachDBExpression0 = CockroachDBConstant.createArrayConstant((List<CockroachDBExpression>) null);
      assertNotNull(cockroachDBExpression0);
  }

  @Test(timeout = 4000)
  public void test24()  throws Throwable  {
      CockroachDBConstant cockroachDBConstant0 = CockroachDBConstant.createBooleanConstant(true);
      String string0 = ((CockroachDBConstant.CockroachDBBooleanConstant) cockroachDBConstant0).toString();
      assertEquals("true", string0);
  }

  @Test(timeout = 4000)
  public void test25()  throws Throwable  {
      CockroachDBConstant.CockroachDBIntConstant cockroachDBConstant_CockroachDBIntConstant0 = CockroachDBConstant.createIntConstant(9223372036854775807L);
      assertEquals("9223372036854775807", cockroachDBConstant_CockroachDBIntConstant0.toString());
  }

  @Test(timeout = 4000)
  public void test26()  throws Throwable  {
      CockroachDBExpression cockroachDBExpression0 = CockroachDBConstant.createTimeConstant(0L);
      assertNotNull(cockroachDBExpression0);
  }

  @Test(timeout = 4000)
  public void test27()  throws Throwable  {
      CockroachDBConstant.CockroachDBTextConstant cockroachDBConstant_CockroachDBTextConstant0 = CockroachDBConstant.createStringConstant("`]uT///");
      assertEquals("`]uT///", cockroachDBConstant_CockroachDBTextConstant0.getValue());
  }

  @Test(timeout = 4000)
  public void test28()  throws Throwable  {
      CockroachDBExpression cockroachDBExpression0 = CockroachDBConstant.createTimestampConstant((-755L));
      assertNotNull(cockroachDBExpression0);
  }

  @Test(timeout = 4000)
  public void test29()  throws Throwable  {
      CockroachDBConstant.CockroachDBNullConstant cockroachDBConstant_CockroachDBNullConstant0 = CockroachDBConstant.createNullConstant();
      String string0 = cockroachDBConstant_CockroachDBNullConstant0.toString();
      assertEquals("NULL", string0);
  }

  @Test(timeout = 4000)
  public void test30()  throws Throwable  {
      CockroachDBExpression cockroachDBExpression0 = CockroachDBConstant.createTimetz(0L);
      assertNotNull(cockroachDBExpression0);
  }

  @Test(timeout = 4000)
  public void test31()  throws Throwable  {
      CockroachDBConstant.CockroachDBDoubleConstant cockroachDBConstant_CockroachDBDoubleConstant0 = CockroachDBConstant.createFloatConstant(205);
      String string0 = cockroachDBConstant_CockroachDBDoubleConstant0.toString();
      assertEquals("205.0", string0);
  }

  @Test(timeout = 4000)
  public void test32()  throws Throwable  {
      CockroachDBConstant.CockroachDBBitConstant cockroachDBConstant_CockroachDBBitConstant0 = (CockroachDBConstant.CockroachDBBitConstant)CockroachDBConstant.createBitConstant(205);
      assertEquals("11001101", cockroachDBConstant_CockroachDBBitConstant0.getValue());
  }

  @Test(timeout = 4000)
  public void test33()  throws Throwable  {
      CockroachDBConstant.CockroachDBDoubleConstant cockroachDBConstant_CockroachDBDoubleConstant0 = new CockroachDBConstant.CockroachDBDoubleConstant((-777.47));
      double double0 = cockroachDBConstant_CockroachDBDoubleConstant0.getValue();
      assertEquals((-777.47), double0, 0.01);
  }
}
