/**
 * Scaffolding file used to store all the setups needed to run 
 * tests automatically generated by EvoSuite
 * Mon Apr 14 08:55:18 GMT 2025
 */

package sqlancer.databend.test.tlp;

import org.evosuite.runtime.annotation.EvoSuiteClassExclude;
import org.junit.BeforeClass;
import org.junit.Before;
import org.junit.After;
import org.junit.AfterClass;
import org.evosuite.runtime.sandbox.Sandbox;
import org.evosuite.runtime.sandbox.Sandbox.SandboxMode;

@EvoSuiteClassExclude
public class DatabendQueryPartitioningBase_ESTest_scaffolding {

  @org.junit.Rule
  public org.evosuite.runtime.vnet.NonFunctionalRequirementRule nfr = new org.evosuite.runtime.vnet.NonFunctionalRequirementRule();

  private static final java.util.Properties defaultProperties = (java.util.Properties) java.lang.System.getProperties().clone(); 

  private org.evosuite.runtime.thread.ThreadStopper threadStopper =  new org.evosuite.runtime.thread.ThreadStopper (org.evosuite.runtime.thread.KillSwitchHandler.getInstance(), 3000);


  @BeforeClass
  public static void initEvoSuiteFramework() { 
    org.evosuite.runtime.RuntimeSettings.className = "sqlancer.databend.test.tlp.DatabendQueryPartitioningBase"; 
    org.evosuite.runtime.GuiSupport.initialize(); 
    org.evosuite.runtime.RuntimeSettings.maxNumberOfThreads = 100; 
    org.evosuite.runtime.RuntimeSettings.maxNumberOfIterationsPerLoop = 10000; 
    org.evosuite.runtime.RuntimeSettings.mockSystemIn = true; 
    org.evosuite.runtime.RuntimeSettings.sandboxMode = org.evosuite.runtime.sandbox.Sandbox.SandboxMode.RECOMMENDED; 
    org.evosuite.runtime.sandbox.Sandbox.initializeSecurityManagerForSUT(); 
    org.evosuite.runtime.classhandling.JDKClassResetter.init();
    setSystemProperties();
    initializeClasses();
    org.evosuite.runtime.Runtime.getInstance().resetRuntime(); 
  } 

  @AfterClass
  public static void clearEvoSuiteFramework(){ 
    Sandbox.resetDefaultSecurityManager(); 
    java.lang.System.setProperties((java.util.Properties) defaultProperties.clone()); 
  } 

  @Before
  public void initTestCase(){ 
    threadStopper.storeCurrentThreads();
    threadStopper.startRecordingTime();
    org.evosuite.runtime.jvm.ShutdownHookHandler.getInstance().initHandler(); 
    org.evosuite.runtime.sandbox.Sandbox.goingToExecuteSUTCode(); 
    setSystemProperties(); 
    org.evosuite.runtime.GuiSupport.setHeadless(); 
    org.evosuite.runtime.Runtime.getInstance().resetRuntime(); 
    org.evosuite.runtime.agent.InstrumentingAgent.activate(); 
  } 

  @After
  public void doneWithTestCase(){ 
    threadStopper.killAndJoinClientThreads();
    org.evosuite.runtime.jvm.ShutdownHookHandler.getInstance().safeExecuteAddedHooks(); 
    org.evosuite.runtime.classhandling.JDKClassResetter.reset(); 
    resetClasses(); 
    org.evosuite.runtime.sandbox.Sandbox.doneWithExecutingSUTCode(); 
    org.evosuite.runtime.agent.InstrumentingAgent.deactivate(); 
    org.evosuite.runtime.GuiSupport.restoreHeadlessMode(); 
  } 

  public static void setSystemProperties() {
 
    java.lang.System.setProperties((java.util.Properties) defaultProperties.clone()); 
    java.lang.System.setProperty("java.io.tmpdir", "C:\\Users\\hp\\AppData\\Local\\Temp\\"); 
    java.lang.System.setProperty("user.dir", "E:\\Y2S2\\CS3213\\Sqlancer_original"); 
  }

  private static void initializeClasses() {
    org.evosuite.runtime.classhandling.ClassStateSupport.initializeClasses(DatabendQueryPartitioningBase_ESTest_scaffolding.class.getClassLoader() ,
      "sqlancer.databend.DatabendSchema$DatabendTable",
      "sqlancer.AbstractAction",
      "sqlancer.common.gen.NoRECGenerator",
      "sqlancer.StatementExecutor",
      "sqlancer.databend.DatabendProvider$DatabendGlobalState",
      "sqlancer.SQLProviderAdapter",
      "sqlancer.databend.DatabendProvider",
      "sqlancer.common.gen.ExpressionGenerator",
      "sqlancer.databend.DatabendBugs",
      "sqlancer.Randomly$StringGenerationStrategy",
      "sqlancer.databend.DatabendErrors",
      "sqlancer.databend.DatabendSchema",
      "sqlancer.Main$StateLogger",
      "sqlancer.common.schema.AbstractTable",
      "sqlancer.databend.DatabendSchema$DatabendCompositeDataType",
      "sqlancer.common.query.ExpectedErrors",
      "sqlancer.GlobalState",
      "sqlancer.common.ast.newast.Select",
      "sqlancer.databend.DatabendSchema$DatabendRowValue",
      "sqlancer.common.schema.AbstractSchema",
      "sqlancer.DatabaseProvider",
      "sqlancer.databend.DatabendSchema$DatabendTables",
      "sqlancer.common.gen.PartitionGenerator",
      "sqlancer.common.schema.AbstractRelationalTable",
      "sqlancer.Main$QueryManager",
      "sqlancer.databend.ast.DatabendSelect",
      "sqlancer.common.gen.TypedExpressionGenerator",
      "sqlancer.ProviderAdapter",
      "sqlancer.common.query.Query",
      "sqlancer.databend.test.tlp.DatabendQueryPartitioningBase",
      "sqlancer.databend.ast.DatabendTableReference",
      "sqlancer.SQLancerDBConnection",
      "sqlancer.MainOptions",
      "sqlancer.common.ast.newast.ColumnReferenceNode",
      "sqlancer.Randomly",
      "sqlancer.common.oracle.TestOracle",
      "sqlancer.common.gen.TLPWhereGenerator",
      "sqlancer.common.schema.AbstractTableColumn",
      "sqlancer.common.query.SQLancerResultSet",
      "sqlancer.databend.ast.DatabendColumnValue",
      "sqlancer.databend.DatabendProvider$Action",
      "sqlancer.common.ast.newast.Expression",
      "sqlancer.SQLGlobalState",
      "sqlancer.Randomly$StringGenerationStrategy$4",
      "sqlancer.Randomly$StringGenerationStrategy$3",
      "sqlancer.StateToReproduce",
      "sqlancer.Randomly$StringGenerationStrategy$2",
      "sqlancer.Randomly$StringGenerationStrategy$1",
      "sqlancer.databend.gen.DatabendNewExpressionGenerator",
      "sqlancer.SQLConnection",
      "sqlancer.databend.DatabendSchema$DatabendColumn",
      "sqlancer.databend.DatabendSchema$DatabendDataType",
      "sqlancer.DBMSSpecificOptions",
      "sqlancer.databend.ast.DatabendColumnReference",
      "sqlancer.IgnoreMeException",
      "sqlancer.common.log.Loggable",
      "sqlancer.common.ast.SelectBase",
      "sqlancer.common.schema.AbstractRowValue",
      "sqlancer.databend.ast.DatabendExpression",
      "sqlancer.common.schema.AbstractTables",
      "sqlancer.common.oracle.TernaryLogicPartitioningOracleBase",
      "sqlancer.Reproducer",
      "sqlancer.common.ast.newast.TableReferenceNode"
    );
  } 

  private static void resetClasses() {
    org.evosuite.runtime.classhandling.ClassResetter.getInstance().setClassLoader(DatabendQueryPartitioningBase_ESTest_scaffolding.class.getClassLoader()); 

    org.evosuite.runtime.classhandling.ClassStateSupport.resetClasses(
      "sqlancer.common.oracle.TernaryLogicPartitioningOracleBase",
      "sqlancer.databend.test.tlp.DatabendQueryPartitioningBase",
      "sqlancer.databend.DatabendBugs",
      "sqlancer.databend.ast.DatabendJoin",
      "sqlancer.databend.ast.DatabendJoin$JoinType",
      "sqlancer.Randomly$StringGenerationStrategy$4",
      "sqlancer.Randomly$StringGenerationStrategy",
      "sqlancer.Randomly",
      "sqlancer.databend.DatabendSchema$DatabendDataType",
      "sqlancer.databend.ast.DatabendJoin$OuterType",
      "sqlancer.GlobalState",
      "sqlancer.SQLGlobalState",
      "sqlancer.databend.DatabendProvider$DatabendGlobalState",
      "sqlancer.common.query.Query",
      "sqlancer.common.query.SQLQueryAdapter",
      "sqlancer.common.query.SQLQueryResultCheckAdapter",
      "sqlancer.common.query.ExpectedErrors",
      "sqlancer.databend.DatabendErrors",
      "sqlancer.common.query.ExpectedErrors$ExpectedErrorsBuilder",
      "sqlancer.common.schema.AbstractSchema",
      "sqlancer.databend.DatabendSchema",
      "sqlancer.postgres.PostgresGlobalState",
      "sqlancer.citus.CitusGlobalState",
      "sqlancer.materialize.MaterializeGlobalState",
      "sqlancer.common.ast.SelectBase",
      "sqlancer.databend.ast.DatabendSelect",
      "sqlancer.SQLConnection",
      "sqlancer.common.gen.TypedExpressionGenerator",
      "sqlancer.databend.gen.DatabendNewExpressionGenerator",
      "sqlancer.common.schema.AbstractTables",
      "sqlancer.databend.DatabendSchema$DatabendTables",
      "sqlancer.databend.ast.DatabendConstant",
      "sqlancer.databend.ast.DatabendConstant$DatabendTimestampConstant",
      "sqlancer.common.ast.newast.NewFunctionNode",
      "sqlancer.databend.ast.DatabendFunctionOperation",
      "sqlancer.databend.ast.DatabendConstant$DatabendIntConstant",
      "sqlancer.databend.ast.DatabendConstant$DatabendBooleanConstant",
      "sqlancer.databend.ast.DatabendConstant$DatabendFloatConstant",
      "sqlancer.databend.ast.DatabendUnaryPrefixOperation$DatabendUnaryPrefixOperator",
      "sqlancer.common.ast.newast.NewBinaryOperatorNode",
      "sqlancer.databend.ast.DatabendBinaryOperation",
      "sqlancer.common.ast.newast.NewToStringVisitor",
      "sqlancer.databend.DatabendToStringVisitor",
      "sqlancer.databend.ast.DatabendConstant$DatabendStringConstant",
      "sqlancer.databend.ast.DatabendConstant$DatabendDateConstant",
      "sqlancer.common.schema.AbstractTable",
      "sqlancer.common.schema.AbstractRelationalTable",
      "sqlancer.databend.DatabendSchema$DatabendTable",
      "sqlancer.databend.ast.DatabendConstant$DatabendNullConstant",
      "sqlancer.common.ast.newast.ColumnReferenceNode",
      "sqlancer.databend.ast.DatabendColumnReference",
      "sqlancer.common.schema.AbstractTableColumn",
      "sqlancer.databend.DatabendSchema$DatabendColumn"
    );
  }
}
