/*
 * This file was automatically generated by EvoSuite
 * Mon Apr 14 08:16:06 GMT 2025
 */

package sqlancer.databend.test.tlp;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;
import sqlancer.databend.DatabendProvider;
import sqlancer.databend.test.tlp.DatabendQueryPartitioningDistinctTester;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true) 
public class DatabendQueryPartitioningDistinctTester_ESTest extends DatabendQueryPartitioningDistinctTester_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      DatabendProvider.DatabendGlobalState databendProvider_DatabendGlobalState0 = new DatabendProvider.DatabendGlobalState();
      DatabendQueryPartitioningDistinctTester databendQueryPartitioningDistinctTester0 = new DatabendQueryPartitioningDistinctTester(databendProvider_DatabendGlobalState0);
      // Undeclared exception!
      try { 
        databendQueryPartitioningDistinctTester0.check();
        fail("Expecting exception: AssertionError");
      
      } catch(AssertionError e) {
         //
         // null
         //
      }
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      DatabendQueryPartitioningDistinctTester databendQueryPartitioningDistinctTester0 = new DatabendQueryPartitioningDistinctTester((DatabendProvider.DatabendGlobalState) null);
      // Undeclared exception!
      try { 
        databendQueryPartitioningDistinctTester0.check();
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("sqlancer.databend.test.tlp.DatabendQueryPartitioningBase", e);
      }
  }
}
