/**
 * Scaffolding file used to store all the setups needed to run 
 * tests automatically generated by EvoSuite
 * Sun Apr 13 13:12:14 GMT 2025
 */

package sqlancer.clickhouse.ast;

import org.evosuite.runtime.annotation.EvoSuiteClassExclude;
import org.junit.BeforeClass;
import org.junit.Before;
import org.junit.After;
import org.junit.AfterClass;
import org.evosuite.runtime.sandbox.Sandbox;
import org.evosuite.runtime.sandbox.Sandbox.SandboxMode;

@EvoSuiteClassExclude
public class ClickHouseBinaryArithmeticOperation_ESTest_scaffolding {

  @org.junit.Rule
  public org.evosuite.runtime.vnet.NonFunctionalRequirementRule nfr = new org.evosuite.runtime.vnet.NonFunctionalRequirementRule();

  private static final java.util.Properties defaultProperties = (java.util.Properties) java.lang.System.getProperties().clone(); 

  private org.evosuite.runtime.thread.ThreadStopper threadStopper =  new org.evosuite.runtime.thread.ThreadStopper (org.evosuite.runtime.thread.KillSwitchHandler.getInstance(), 3000);


  @BeforeClass
  public static void initEvoSuiteFramework() { 
    org.evosuite.runtime.RuntimeSettings.className = "sqlancer.clickhouse.ast.ClickHouseBinaryArithmeticOperation"; 
    org.evosuite.runtime.GuiSupport.initialize(); 
    org.evosuite.runtime.RuntimeSettings.maxNumberOfThreads = 100; 
    org.evosuite.runtime.RuntimeSettings.maxNumberOfIterationsPerLoop = 10000; 
    org.evosuite.runtime.RuntimeSettings.mockSystemIn = true; 
    org.evosuite.runtime.RuntimeSettings.sandboxMode = org.evosuite.runtime.sandbox.Sandbox.SandboxMode.RECOMMENDED; 
    org.evosuite.runtime.sandbox.Sandbox.initializeSecurityManagerForSUT(); 
    org.evosuite.runtime.classhandling.JDKClassResetter.init();
    setSystemProperties();
    initializeClasses();
    org.evosuite.runtime.Runtime.getInstance().resetRuntime(); 
  } 

  @AfterClass
  public static void clearEvoSuiteFramework(){ 
    Sandbox.resetDefaultSecurityManager(); 
    java.lang.System.setProperties((java.util.Properties) defaultProperties.clone()); 
  } 

  @Before
  public void initTestCase(){ 
    threadStopper.storeCurrentThreads();
    threadStopper.startRecordingTime();
    org.evosuite.runtime.jvm.ShutdownHookHandler.getInstance().initHandler(); 
    org.evosuite.runtime.sandbox.Sandbox.goingToExecuteSUTCode(); 
    setSystemProperties(); 
    org.evosuite.runtime.GuiSupport.setHeadless(); 
    org.evosuite.runtime.Runtime.getInstance().resetRuntime(); 
    org.evosuite.runtime.agent.InstrumentingAgent.activate(); 
  } 

  @After
  public void doneWithTestCase(){ 
    threadStopper.killAndJoinClientThreads();
    org.evosuite.runtime.jvm.ShutdownHookHandler.getInstance().safeExecuteAddedHooks(); 
    org.evosuite.runtime.classhandling.JDKClassResetter.reset(); 
    resetClasses(); 
    org.evosuite.runtime.sandbox.Sandbox.doneWithExecutingSUTCode(); 
    org.evosuite.runtime.agent.InstrumentingAgent.deactivate(); 
    org.evosuite.runtime.GuiSupport.restoreHeadlessMode(); 
  } 

  public static void setSystemProperties() {
 
    java.lang.System.setProperties((java.util.Properties) defaultProperties.clone()); 
    java.lang.System.setProperty("user.dir", "E:\\Y2S2\\CS3213\\Sqlancer_original"); 
    java.lang.System.setProperty("java.io.tmpdir", "C:\\Users\\hp\\AppData\\Local\\Temp\\"); 
  }

  private static void initializeClasses() {
    org.evosuite.runtime.classhandling.ClassStateSupport.initializeClasses(ClickHouseBinaryArithmeticOperation_ESTest_scaffolding.class.getClassLoader() ,
      "sqlancer.clickhouse.ast.ClickHouseBinaryArithmeticOperation",
      "sqlancer.common.ast.newast.Select",
      "sqlancer.Randomly",
      "sqlancer.clickhouse.ast.ClickHouseExpression",
      "sqlancer.common.schema.AbstractSchema",
      "sqlancer.clickhouse.ast.ClickHouseSelect",
      "sqlancer.clickhouse.ast.constant.ClickHouseStringConstant",
      "sqlancer.common.visitor.BinaryOperation",
      "sqlancer.clickhouse.ClickHouseSchema",
      "sqlancer.clickhouse.ast.constant.ClickHouseInt32Constant",
      "sqlancer.clickhouse.ast.ClickHouseSelect$SelectType",
      "sqlancer.Randomly$StringGenerationStrategy",
      "sqlancer.IgnoreMeException",
      "sqlancer.clickhouse.ast.ClickHouseExpression$ClickHouseExist",
      "sqlancer.clickhouse.ast.ClickHouseBinaryArithmeticOperation$ClickHouseBinaryArithmeticOperator",
      "sqlancer.common.ast.newast.Expression",
      "sqlancer.Randomly$StringGenerationStrategy$4",
      "sqlancer.Randomly$StringGenerationStrategy$3",
      "sqlancer.Randomly$StringGenerationStrategy$2",
      "sqlancer.clickhouse.ast.ClickHouseConstant",
      "sqlancer.Randomly$StringGenerationStrategy$1"
    );
  } 

  private static void resetClasses() {
    org.evosuite.runtime.classhandling.ClassResetter.getInstance().setClassLoader(ClickHouseBinaryArithmeticOperation_ESTest_scaffolding.class.getClassLoader()); 

    org.evosuite.runtime.classhandling.ClassStateSupport.resetClasses(
      "sqlancer.clickhouse.ast.ClickHouseExpression",
      "sqlancer.clickhouse.ast.ClickHouseBinaryArithmeticOperation",
      "sqlancer.clickhouse.ast.ClickHouseBinaryArithmeticOperation$ClickHouseBinaryArithmeticOperator",
      "sqlancer.clickhouse.ast.ClickHouseConstant",
      "sqlancer.clickhouse.ast.constant.ClickHouseUInt256Constant",
      "sqlancer.clickhouse.ast.ClickHouseCast",
      "sqlancer.clickhouse.ast.constant.ClickHouseUInt8Constant",
      "sqlancer.common.schema.AbstractTableColumn",
      "sqlancer.clickhouse.ClickHouseSchema$ClickHouseColumn",
      "sqlancer.clickhouse.ClickHouseSchema$ClickHouseLancerDataType",
      "sqlancer.clickhouse.ast.ClickHouseTableReference",
      "sqlancer.clickhouse.ast.ClickHouseExpression$ClickHouseJoinOnClause",
      "sqlancer.clickhouse.ast.ClickHouseExpression$ClickHouseJoin",
      "sqlancer.clickhouse.ast.ClickHouseBinaryComparisonOperation",
      "sqlancer.Randomly$StringGenerationStrategy$4",
      "sqlancer.Randomly$StringGenerationStrategy",
      "sqlancer.Randomly",
      "sqlancer.clickhouse.ast.constant.ClickHouseInt32Constant",
      "sqlancer.clickhouse.ast.ClickHouseExpression$ClickHouseExist",
      "sqlancer.clickhouse.ast.constant.ClickHouseStringConstant",
      "sqlancer.clickhouse.ast.ClickHouseSelect",
      "sqlancer.clickhouse.ast.constant.ClickHouseFloat64Constant",
      "sqlancer.clickhouse.ast.constant.ClickHouseUInt16Constant",
      "sqlancer.clickhouse.ast.constant.ClickHouseInt128Constant",
      "sqlancer.clickhouse.ast.constant.ClickHouseUInt64Constant",
      "sqlancer.clickhouse.ast.constant.ClickHouseInt16Constant",
      "sqlancer.clickhouse.ast.constant.ClickHouseBooleanConstant",
      "sqlancer.clickhouse.ast.constant.ClickHouseUInt32Constant",
      "sqlancer.clickhouse.ast.constant.ClickHouseNullConstant",
      "sqlancer.clickhouse.ast.ClickHouseBinaryFunctionOperation",
      "sqlancer.clickhouse.ast.ClickHouseUnaryFunctionOperation",
      "sqlancer.common.visitor.UnaryOperation$OperatorKind",
      "sqlancer.clickhouse.ast.constant.ClickHouseInt8Constant",
      "sqlancer.clickhouse.ast.ClickHouseUnaryPostfixOperation",
      "sqlancer.common.visitor.NodeVisitor",
      "sqlancer.common.visitor.ToStringVisitor",
      "sqlancer.clickhouse.ClickHouseToStringVisitor",
      "sqlancer.clickhouse.ast.ClickHouseExpression$ClickHouseSubquery",
      "sqlancer.clickhouse.ast.constant.ClickHouseInt64Constant",
      "sqlancer.clickhouse.ast.constant.ClickHouseFloat32Constant",
      "sqlancer.clickhouse.ast.ClickHouseAliasOperation",
      "sqlancer.clickhouse.ast.constant.ClickHouseInt256Constant",
      "sqlancer.clickhouse.ast.constant.ClickHouseUInt128Constant",
      "sqlancer.clickhouse.ast.ClickHouseExpression$ClickHousePostfixText",
      "sqlancer.common.schema.AbstractTable",
      "sqlancer.common.schema.AbstractRelationalTable",
      "sqlancer.clickhouse.ClickHouseSchema$ClickHouseTable",
      "sqlancer.clickhouse.ast.ClickHouseUnaryPrefixOperation",
      "sqlancer.clickhouse.ast.ClickHouseBinaryLogicalOperation",
      "sqlancer.clickhouse.ast.constant.ClickHouseCreateConstant",
      "sqlancer.clickhouse.ast.ClickHouseAggregate",
      "sqlancer.clickhouse.ast.ClickHouseColumnReference",
      "sqlancer.clickhouse.ast.ClickHouseCastOperation",
      "sqlancer.clickhouse.ast.ClickHouseSelect$SelectType"
    );
  }
}
