/**
 * Scaffolding file used to store all the setups needed to run 
 * tests automatically generated by EvoSuite
 * Mon Apr 14 11:53:47 GMT 2025
 */

package sqlancer.mysql;

import org.evosuite.runtime.annotation.EvoSuiteClassExclude;
import org.junit.BeforeClass;
import org.junit.Before;
import org.junit.After;
import org.junit.AfterClass;
import org.evosuite.runtime.sandbox.Sandbox;
import org.evosuite.runtime.sandbox.Sandbox.SandboxMode;

@EvoSuiteClassExclude
public class MySQLProvider_ESTest_scaffolding {

  @org.junit.Rule
  public org.evosuite.runtime.vnet.NonFunctionalRequirementRule nfr = new org.evosuite.runtime.vnet.NonFunctionalRequirementRule();

  private static final java.util.Properties defaultProperties = (java.util.Properties) java.lang.System.getProperties().clone(); 

  private org.evosuite.runtime.thread.ThreadStopper threadStopper =  new org.evosuite.runtime.thread.ThreadStopper (org.evosuite.runtime.thread.KillSwitchHandler.getInstance(), 3000);


  @BeforeClass
  public static void initEvoSuiteFramework() { 
    org.evosuite.runtime.RuntimeSettings.className = "sqlancer.mysql.MySQLProvider"; 
    org.evosuite.runtime.GuiSupport.initialize(); 
    org.evosuite.runtime.RuntimeSettings.maxNumberOfThreads = 100; 
    org.evosuite.runtime.RuntimeSettings.maxNumberOfIterationsPerLoop = 10000; 
    org.evosuite.runtime.RuntimeSettings.mockSystemIn = true; 
    org.evosuite.runtime.RuntimeSettings.sandboxMode = org.evosuite.runtime.sandbox.Sandbox.SandboxMode.RECOMMENDED; 
    org.evosuite.runtime.sandbox.Sandbox.initializeSecurityManagerForSUT(); 
    org.evosuite.runtime.classhandling.JDKClassResetter.init();
    setSystemProperties();
    initializeClasses();
    org.evosuite.runtime.Runtime.getInstance().resetRuntime(); 
  } 

  @AfterClass
  public static void clearEvoSuiteFramework(){ 
    Sandbox.resetDefaultSecurityManager(); 
    java.lang.System.setProperties((java.util.Properties) defaultProperties.clone()); 
  } 

  @Before
  public void initTestCase(){ 
    threadStopper.storeCurrentThreads();
    threadStopper.startRecordingTime();
    org.evosuite.runtime.jvm.ShutdownHookHandler.getInstance().initHandler(); 
    org.evosuite.runtime.sandbox.Sandbox.goingToExecuteSUTCode(); 
    setSystemProperties(); 
    org.evosuite.runtime.GuiSupport.setHeadless(); 
    org.evosuite.runtime.Runtime.getInstance().resetRuntime(); 
    org.evosuite.runtime.agent.InstrumentingAgent.activate(); 
  } 

  @After
  public void doneWithTestCase(){ 
    threadStopper.killAndJoinClientThreads();
    org.evosuite.runtime.jvm.ShutdownHookHandler.getInstance().safeExecuteAddedHooks(); 
    org.evosuite.runtime.classhandling.JDKClassResetter.reset(); 
    resetClasses(); 
    org.evosuite.runtime.sandbox.Sandbox.doneWithExecutingSUTCode(); 
    org.evosuite.runtime.agent.InstrumentingAgent.deactivate(); 
    org.evosuite.runtime.GuiSupport.restoreHeadlessMode(); 
  } 

  public static void setSystemProperties() {
 
    java.lang.System.setProperties((java.util.Properties) defaultProperties.clone()); 
    java.lang.System.setProperty("user.dir", "E:\\Y2S2\\CS3213\\Sqlancer_original"); 
    java.lang.System.setProperty("java.io.tmpdir", "C:\\Users\\hp\\AppData\\Local\\Temp\\"); 
  }

  private static void initializeClasses() {
    org.evosuite.runtime.classhandling.ClassStateSupport.initializeClasses(MySQLProvider_ESTest_scaffolding.class.getClassLoader() ,
      "sqlancer.common.log.SQLLoggableFactory",
      "sqlancer.mysql.gen.tblmaintenance.MySQLChecksum",
      "sqlancer.mysql.gen.admin.MySQLReset",
      "sqlancer.mysql.gen.MySQLUpdateGenerator",
      "sqlancer.AbstractAction",
      "sqlancer.OracleFactory",
      "sqlancer.mysql.gen.datadef.MySQLIndexGenerator",
      "sqlancer.StatementExecutor",
      "sqlancer.mysql.MySQLProvider",
      "sqlancer.SQLProviderAdapter",
      "sqlancer.mysql.gen.tblmaintenance.MySQLOptimize",
      "sqlancer.Main$StateLogger",
      "sqlancer.mysql.gen.MySQLInsertGenerator",
      "sqlancer.mysql.MySQLOptions",
      "sqlancer.common.log.LoggableFactory",
      "sqlancer.common.schema.AbstractTable",
      "sqlancer.common.query.ExpectedErrors",
      "sqlancer.GlobalState",
      "sqlancer.common.schema.AbstractSchema",
      "sqlancer.mysql.gen.admin.MySQLFlush",
      "sqlancer.DatabaseProvider",
      "sqlancer.common.schema.AbstractRelationalTable",
      "sqlancer.Main$QueryManager",
      "sqlancer.mysql.gen.tblmaintenance.MySQLCheckTable",
      "sqlancer.mysql.gen.MySQLSetGenerator",
      "sqlancer.ProviderAdapter",
      "sqlancer.common.query.Query",
      "sqlancer.mysql.gen.MySQLDropIndex",
      "sqlancer.mysql.MySQLOracleFactory",
      "sqlancer.mysql.gen.tblmaintenance.MySQLRepair",
      "sqlancer.mysql.gen.MySQLDeleteGenerator",
      "sqlancer.SQLancerDBConnection",
      "sqlancer.mysql.MySQLSchema$MySQLTable",
      "sqlancer.MainOptions",
      "sqlancer.Randomly",
      "sqlancer.common.oracle.TestOracle",
      "sqlancer.common.query.SQLancerResultSet",
      "sqlancer.common.query.SQLQueryAdapter",
      "sqlancer.common.query.SQLQueryProvider",
      "sqlancer.mysql.gen.MySQLTruncateTableGenerator",
      "sqlancer.SQLGlobalState",
      "sqlancer.mysql.MySQLProvider$Action",
      "sqlancer.mysql.gen.MySQLAlterTable",
      "sqlancer.StateToReproduce",
      "sqlancer.SQLConnection",
      "sqlancer.mysql.MySQLGlobalState",
      "sqlancer.mysql.MySQLSchema",
      "sqlancer.DBMSSpecificOptions",
      "sqlancer.IgnoreMeException",
      "sqlancer.common.log.Loggable",
      "sqlancer.common.gen.AbstractUpdateGenerator",
      "sqlancer.mysql.gen.tblmaintenance.MySQLAnalyzeTable",
      "sqlancer.Reproducer"
    );
  } 

  private static void resetClasses() {
    org.evosuite.runtime.classhandling.ClassResetter.getInstance().setClassLoader(MySQLProvider_ESTest_scaffolding.class.getClassLoader()); 

    org.evosuite.runtime.classhandling.ClassStateSupport.resetClasses(
      "sqlancer.ProviderAdapter",
      "sqlancer.SQLProviderAdapter",
      "sqlancer.mysql.MySQLProvider",
      "sqlancer.mysql.MySQLProvider$Action",
      "sqlancer.Randomly$StringGenerationStrategy$4",
      "sqlancer.Randomly$StringGenerationStrategy",
      "sqlancer.Randomly",
      "sqlancer.mysql.MySQLBugs",
      "sqlancer.mysql.MySQLOracleFactory",
      "sqlancer.GlobalState",
      "sqlancer.SQLGlobalState",
      "sqlancer.mysql.MySQLGlobalState",
      "sqlancer.common.query.ExpectedErrors",
      "sqlancer.common.query.Query",
      "sqlancer.common.query.SQLQueryAdapter",
      "sqlancer.common.query.ExpectedErrors$ExpectedErrorsBuilder",
      "sqlancer.materialize.MaterializeGlobalState",
      "sqlancer.mysql.gen.tblmaintenance.MySQLAnalyzeTable",
      "sqlancer.common.schema.AbstractSchema",
      "sqlancer.mysql.MySQLSchema",
      "sqlancer.StateToReproduce",
      "sqlancer.common.query.SQLQueryResultCheckAdapter",
      "sqlancer.common.log.LoggableFactory",
      "sqlancer.common.log.SQLLoggableFactory",
      "sqlancer.postgres.PostgresGlobalState",
      "sqlancer.citus.CitusGlobalState",
      "sqlancer.mysql.gen.datadef.MySQLIndexGenerator",
      "sqlancer.mysql.gen.admin.MySQLReset",
      "sqlancer.mysql.gen.MySQLInsertGenerator",
      "sqlancer.mysql.gen.MySQLSetGenerator",
      "sqlancer.mysql.gen.admin.MySQLFlush",
      "sqlancer.mysql.gen.tblmaintenance.MySQLOptimize",
      "sqlancer.mysql.gen.MySQLTruncateTableGenerator",
      "sqlancer.common.gen.AbstractUpdateGenerator",
      "sqlancer.mysql.gen.MySQLUpdateGenerator",
      "sqlancer.mysql.gen.MySQLAlterTable",
      "sqlancer.mysql.gen.MySQLDropIndex",
      "sqlancer.mysql.gen.tblmaintenance.MySQLCheckTable",
      "sqlancer.mysql.gen.tblmaintenance.MySQLRepair",
      "sqlancer.mysql.gen.MySQLDeleteGenerator",
      "sqlancer.doris.DorisProvider$DorisGlobalState",
      "sqlancer.mysql.gen.tblmaintenance.MySQLChecksum",
      "sqlancer.databend.DatabendProvider$DatabendGlobalState",
      "sqlancer.SQLConnection"
    );
  }
}
