/*
 * This file was automatically generated by EvoSuite
 * Mon Apr 14 04:03:58 GMT 2025
 */

package sqlancer.cnosdb.client;

import org.junit.Test;
import static org.junit.Assert.*;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;
import sqlancer.cnosdb.client.CnosDBException;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true) 
public class CnosDBException_ESTest extends CnosDBException_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      CnosDBException cnosDBException0 = new CnosDBException("72ff");
  }
}
