/*
 * This file was automatically generated by EvoSuite
 * Sun Apr 13 14:28:55 GMT 2025
 */

package sqlancer.cnosdb.oracle.tlp;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;
import sqlancer.cnosdb.CnosDBGlobalState;
import sqlancer.cnosdb.oracle.tlp.CnosDBTLPAggregateOracle;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true) 
public class CnosDBTLPAggregateOracle_ESTest extends CnosDBTLPAggregateOracle_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      CnosDBGlobalState cnosDBGlobalState0 = new CnosDBGlobalState();
      CnosDBTLPAggregateOracle cnosDBTLPAggregateOracle0 = new CnosDBTLPAggregateOracle(cnosDBGlobalState0);
      // Undeclared exception!
      try { 
        cnosDBTLPAggregateOracle0.check();
        fail("Expecting exception: AssertionError");
      
      } catch(AssertionError e) {
         //
         // null
         //
      }
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      CnosDBTLPAggregateOracle cnosDBTLPAggregateOracle0 = new CnosDBTLPAggregateOracle((CnosDBGlobalState) null);
      // Undeclared exception!
      try { 
        cnosDBTLPAggregateOracle0.aggregateCheck();
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("sqlancer.cnosdb.oracle.tlp.CnosDBTLPAggregateOracle", e);
      }
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      CnosDBTLPAggregateOracle cnosDBTLPAggregateOracle0 = new CnosDBTLPAggregateOracle((CnosDBGlobalState) null);
      try { 
        cnosDBTLPAggregateOracle0.check();
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("sqlancer.cnosdb.oracle.tlp.CnosDBTLPBase", e);
      }
  }
}
