/*
 * This file was automatically generated by EvoSuite
 * Sun Apr 13 13:25:44 GMT 2025
 */

package sqlancer.clickhouse.oracle.tlp;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;
import sqlancer.clickhouse.ClickHouseProvider;
import sqlancer.clickhouse.oracle.tlp.ClickHouseTLPDistinctOracle;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true) 
public class ClickHouseTLPDistinctOracle_ESTest extends ClickHouseTLPDistinctOracle_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      ClickHouseProvider.ClickHouseGlobalState clickHouseProvider_ClickHouseGlobalState0 = new ClickHouseProvider.ClickHouseGlobalState();
      ClickHouseTLPDistinctOracle clickHouseTLPDistinctOracle0 = new ClickHouseTLPDistinctOracle(clickHouseProvider_ClickHouseGlobalState0);
      // Undeclared exception!
      try { 
        clickHouseTLPDistinctOracle0.check();
        fail("Expecting exception: AssertionError");
      
      } catch(AssertionError e) {
         //
         // null
         //
      }
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      ClickHouseTLPDistinctOracle clickHouseTLPDistinctOracle0 = new ClickHouseTLPDistinctOracle((ClickHouseProvider.ClickHouseGlobalState) null);
      // Undeclared exception!
      try { 
        clickHouseTLPDistinctOracle0.check();
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("sqlancer.clickhouse.oracle.tlp.ClickHouseTLPBase", e);
      }
  }
}
